type: 'directory'
id: '18MuB6MrJPVEBSBTsAsVJKsqUQbVtSijh'
title: 'Absence Management'
fileName: 'absence-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-09-30T18:34:03.743Z'
version: '171'
fileMap:
  absence-management-workflow.md:
    type: 'md'
    id: '1roXM4bfVNegGsN3YysFAf2cNeolfM4vpce6RmeImvZU'
    title: 'Absence Management Workflow'
    modifiedTime: '2022-01-04T12:11:47.967Z'
    version: 126
    mimeType: 'text/x-markdown'
    lastAuthor: 'Angie Nichols'
    fileName: 'absence-management-workflow.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
