type: 'directory'
id: '18MuB6MrJPVEBSBTsAsVJKsqUQbVtSijh'
title: 'Absence Management'
fileName: 'absence-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-09-30T18:34:03.743Z'
version: '169'
fileMap:
  absence-management-workflow.md:
    type: 'md'
    id: '1roXM4bfVNegGsN3YysFAf2cNeolfM4vpce6RmeImvZU'
    title: 'Absence Management Workflow'
    modifiedTime: '2022-01-04T12:11:47.967Z'
    version: 119
    mimeType: 'text/x-markdown'
    lastAuthor: 'Angie Nichols'
    fileName: 'absence-management-workflow.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
