type: 'directory'
id: '1cd7hs06zA0YvezOax9PEJk7wgHbKUmU6'
title: 'Programs'
fileName: 'programs'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:50.928Z'
version: '79'
fileMap:
  medical-programs.md:
    type: 'md'
    id: '1qfdYxyVgYVpx-5CSpa9MgE22iijISUGMA-5Kg4Zd9jU'
    title: 'Medical Programs'
    modifiedTime: '2021-03-22T22:40:59.826Z'
    version: 67
    mimeType: 'text/x-markdown'
    lastAuthor: 'Grzegorz Godlewski'
    fileName: 'medical-programs.md'
  compliance-programs.md:
    type: 'md'
    id: '1D-Ah67z4hSAKLf0PITZr19h2pvlg3rVBva6P3yl1bno'
    title: 'Compliance Programs'
    modifiedTime: '2021-02-23T18:41:07.730Z'
    version: 30
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'compliance-programs.md'
  quality-reporting.md:
    type: 'md'
    id: '1trmJBS-LCTGZHK9_TvFwTxl9ZQjr8cE-pGn9-aEy6rI'
    title: 'Quality Reporting'
    modifiedTime: '2020-02-27T21:26:25.410Z'
    version: 39
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'quality-reporting.md'
  employee-assistance-program.md:
    type: 'md'
    id: '1j0P-A7K9-lWMUiN-sX5Ez7XPFEDX-FKlFNzfNC5rBy8'
    title: 'Employee Assistance Program'
    modifiedTime: '2020-02-27T19:30:51.715Z'
    version: 36
    mimeType: 'text/x-markdown'
    fileName: 'employee-assistance-program.md'
  quality-reporting:
    type: 'directory'
    id: '17-NcVAnFsowz9Jlwf3unnYeOTf_PPkXC'
    title: 'Quality Reporting'
    modifiedTime: '2020-02-27T19:24:42.968Z'
    version: 275
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'quality-reporting'
  compliance-programs:
    type: 'directory'
    id: '1EgCM1yWElBTgEhlKFrUM5XvBBJm-AnLi'
    title: 'Compliance Programs'
    modifiedTime: '2020-02-27T19:23:55.871Z'
    version: 60
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'compliance-programs'
  medical-programs:
    type: 'directory'
    id: '1rIuz5kM666moOI4oIV7hxHtJoCJsONt9'
    title: 'Medical Programs'
    modifiedTime: '2020-02-27T19:23:53.251Z'
    version: 90
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'medical-programs'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
