type: 'directory'
id: '1tBOYLUF8geYDb0mrGVbdaMkdxbMkhFPd'
title: 'Document Management'
fileName: 'document-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:01.152Z'
version: '301'
fileMap:
  send-document.md:
    type: 'md'
    id: '1qgX2WvaE1iF3D3xYnwq-xGj80liR7s3hMY3ZXCUf2Ww'
    title: 'Send Document'
    modifiedTime: '2022-03-24T12:38:33.377Z'
    version: 181
    mimeType: 'text/x-markdown'
    lastAuthor: 'Aris Eracleous'
    fileName: 'send-document.md'
  imaging.md:
    type: 'md'
    id: '1a3QmGdXV6MW1Ef2Yu8jPUiRSd8o-WENsm3_OK5roV-U'
    title: 'Imaging'
    modifiedTime: '2020-02-27T19:43:28.703Z'
    version: 20
    mimeType: 'text/x-markdown'
    fileName: 'imaging.md'
  printing-and-print-definitions.md:
    type: 'md'
    id: '1NHBPyY_YvI92JSil-rc3O0Kpu5qYLkdKWZTNjlzQpNY'
    title: 'Printing & Print Definitions'
    modifiedTime: '2020-02-27T19:42:35.386Z'
    version: 20
    mimeType: 'text/x-markdown'
    fileName: 'printing-and-print-definitions.md'
  scanning-and-indexing.md:
    type: 'md'
    id: '1pwmW3emkb6f6tktfbMmtsZOKMk1XGa6a8VtvCQz269w'
    title: 'Scanning & Indexing'
    modifiedTime: '2020-02-27T19:40:46.468Z'
    version: 20
    mimeType: 'text/x-markdown'
    fileName: 'scanning-and-indexing.md'
  documents-and-forms.md:
    type: 'md'
    id: '1F21zNiYq703LscR9rtGl8pZLjtxvozONvXhkaZFefEI'
    title: 'Documents & Forms'
    modifiedTime: '2020-02-27T19:35:41.681Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'documents-and-forms.md'
  imaging:
    type: 'directory'
    id: '1OCAqxWNtXZAyZ70Djd48HrObcrDoLjV2'
    title: 'Imaging'
    modifiedTime: '2020-02-27T19:24:04.690Z'
    version: 282
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'imaging'
  printing-and-print-definitions:
    type: 'directory'
    id: '1RwzLBAHbTXCF1sZvJxCWI0WMe-y1fllC'
    title: 'Printing & Print Definitions'
    modifiedTime: '2020-02-27T19:24:03.648Z'
    version: 299
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'printing-and-print-definitions'
  scanning-and-indexing:
    type: 'directory'
    id: '1BUVpKEev56snIQvY9qZCrm1cg3LGZ4nP'
    title: 'Scanning & Indexing'
    modifiedTime: '2020-02-27T19:24:02.761Z'
    version: 295
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'scanning-and-indexing'
  documents-and-forms:
    type: 'directory'
    id: '19OVY8t3OzRAH8Ly5uYdIEoojjAFfRnz4'
    title: 'Documents & Forms'
    modifiedTime: '2020-02-27T19:24:01.913Z'
    version: 286
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'documents-and-forms'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
