type: 'directory'
id: '1X_EpIib7ft6HgFa24I8qQDLPoSQDI0wa'
title: 'Injection/Immunization Management'
fileName: 'injection-immunization-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:14.703Z'
version: '300'
fileMap:
  injection-tab-with-chirp-interface.md:
    type: 'md'
    id: '1cVM6kOokD8qoZ7i7IdJY4lVB2RIXhgOoDG1fNBPY5kQ'
    title: 'Injection Tab with CHIRP Interface'
    modifiedTime: '2020-03-16T15:14:29.099Z'
    version: 62
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injection-tab-with-chirp-interface.md'
  injection-editor.md:
    type: 'md'
    id: '184cEFR0ZGXqOKRMfcjRH0NFDEQg5mJ9SWlnOiPPOnUs'
    title: 'Injection Editor'
    modifiedTime: '2020-03-16T14:47:58.197Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injection-editor.md'
  injection-program-tab-recording-mass-injections.md:
    type: 'md'
    id: '1CiNab4LMjdlfwFMKuO6BvVHheUHyNqoJCxDsdvuyOPk'
    title: 'Injection Program Tab - Recording Mass Injections'
    modifiedTime: '2020-03-16T14:45:42.136Z'
    version: 59
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injection-program-tab-recording-mass-injections.md'
  injection-tab-vials.md:
    type: 'md'
    id: '11_gJvEXt_A9TeALtLbhxsUzWimA0i3C3qi0TZ1w43dk'
    title: 'Injection Tab - Vials'
    modifiedTime: '2020-03-16T14:41:06.490Z'
    version: 52
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injection-tab-vials.md'
  edit-delete-injections-immunizations.md:
    type: 'md'
    id: '1oP6Hhh_LPanOBoETFuY4S6cL8QxKmuwL_LHThe-QWpI'
    title: 'Edit/Delete Injections/Immunizations'
    modifiedTime: '2020-03-16T14:36:13.205Z'
    version: 53
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'edit-delete-injections-immunizations.md'
  injection-tab.md:
    type: 'md'
    id: '1O4s5YPHkNa_EGcmZ9rlsWai2yIrqQnQrEnQHLnTigTk'
    title: 'Injection Tab'
    modifiedTime: '2020-03-16T14:30:50.543Z'
    version: 74
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injection-tab.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
