type: 'directory'
id: '1VgA7_m1u1YUu9pMh64ZKCQIGhW0yz8W7'
title: 'Patient Registration'
fileName: 'patient-registration'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:00.183Z'
version: '276'
fileMap:
  patient-registration-tab-manual-patient-entry.md:
    type: 'md'
    id: '1GA6KzM8KPyzphmOk3kccJLGA7D0gkzzRLHjVrhVIZo0'
    title: 'Patient Registration Tab - Manual Patient Entry'
    modifiedTime: '2021-04-18T04:58:25.003Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'patient-registration-tab-manual-patient-entry.md'
  medical-contacts-contacts,-relationships,-and-user-patient-relationships.md:
    type: 'md'
    id: '1_S9E96qZpixBS4IVXO2ZLdEppl1vfUFG0jYFhbNpyf8'
    title: 'Medical Contacts - Contacts, Relationships, and User-Patient Relationships'
    modifiedTime: '2020-03-20T21:13:39.925Z'
    version: 68
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'medical-contacts-contacts,-relationships,-and-user-patient-relationships.md'
  medical-record-numbers.md:
    type: 'md'
    id: '1D_nQs-HHtwCcd593e2PFQLLEU5S_i2id3LV6H3JlSKg'
    title: 'Medical Record Numbers'
    modifiedTime: '2020-02-27T19:35:30.353Z'
    version: 42
    mimeType: 'text/x-markdown'
    fileName: 'medical-record-numbers.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
