type: 'directory'
id: '1Nn6hwnNBi-b63JnWaq3dK2_2PsUWykgP'
title: 'Rapid Deployment'
fileName: 'rapid-deployment'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:35.069Z'
version: '61'
fileMap:
  rapid-deployment-agenda.md:
    type: 'md'
    id: '1ezVbJoouKbCwkcPmZ_1Qel6ynv7O33u-T-FJapyN0r8'
    title: 'Rapid Deployment Agenda'
    modifiedTime: '2021-01-29T22:11:51.106Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: 'Will Reiske'
    fileName: 'rapid-deployment-agenda.md'
  rapid-deployment-project-outline.md:
    type: 'md'
    id: '1Q8_sOdW4INet_JyBXaaBHn6ilTvpzvljAb11wgo6XR8'
    title: 'Rapid Deployment Project Outline'
    modifiedTime: '2020-02-27T21:24:04.139Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'rapid-deployment-project-outline.md'
  review-sessions.md:
    type: 'md'
    id: '1Ws2Vhysc7vAiQXeVws2C92oE2Y10i-BYITqCos59cWM'
    title: 'Review Sessions'
    modifiedTime: '2020-02-27T20:33:28.288Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'review-sessions.md'
  getting-down-to-basics.md:
    type: 'md'
    id: '1pNelE3B-olct_hrbdA-rgvh2GpACme1hjf7QBz9Bf_w'
    title: 'Getting Down to Basics'
    modifiedTime: '2020-02-27T20:33:05.282Z'
    version: 55
    mimeType: 'text/x-markdown'
    fileName: 'getting-down-to-basics.md'
  rapid-deployment-data-migration.md:
    type: 'md'
    id: '1OQWE20b-U3zYvhTtkJW-fE_3Vh_8tTBfwhRr2Mqcjvg'
    title: 'Rapid Deployment Data Migration'
    modifiedTime: '2020-02-27T20:32:44.582Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'rapid-deployment-data-migration.md'
  review-sessions:
    type: 'directory'
    id: '1UCGCCHVIraTGq_eCrwxJ5VnO4JfZmuiU'
    title: 'Review Sessions'
    modifiedTime: '2020-02-27T19:24:37.482Z'
    version: 288
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'review-sessions'
  rapid-deployment-data-migration:
    type: 'directory'
    id: '1RZD2sGFjRymsNpRb9RUWctzi58oJUXXb'
    title: 'Rapid Deployment Data Migration'
    modifiedTime: '2020-02-27T19:24:36.680Z'
    version: 289
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'rapid-deployment-data-migration'
  rapid-deployment-agenda:
    type: 'directory'
    id: '1ihkeRpCyj9hti-28qZQoAn7aswYO3rq3'
    title: 'Rapid Deployment Agenda'
    modifiedTime: '2020-02-27T19:24:35.914Z'
    version: 283
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'rapid-deployment-agenda'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
