type: 'directory'
id: '1ihkeRpCyj9hti-28qZQoAn7aswYO3rq3'
title: 'Rapid Deployment Agenda'
fileName: 'rapid-deployment-agenda'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:35.914Z'
version: '283'
fileMap:
  deployment-planning.md:
    type: 'md'
    id: '1-2qldux0qTaW6zChE0BBM1mvXjBFcxCEpbDlUiX0WKQ'
    title: 'Deployment Planning'
    modifiedTime: '2020-02-27T20:41:08.035Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'deployment-planning.md'
  high-level-demonstration-for-core-team.md:
    type: 'md'
    id: '1xTyA4BU2ay6pjQhQS7xAXMSrnpBifugw7pqslWORm9U'
    title: 'High-level Demonstration for Core Team'
    modifiedTime: '2020-02-27T20:41:02.693Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'high-level-demonstration-for-core-team.md'
  project-kick-off-meeting.md:
    type: 'md'
    id: '1zWKxR0xaiAQUa97YXT_jDMOREs4n11thpnoNIF16lVI'
    title: 'Project Kick-off Meeting'
    modifiedTime: '2020-02-27T20:40:57.215Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'project-kick-off-meeting.md'
  deployment-planning:
    type: 'directory'
    id: '1GcGWDbh6TyiQu3tK6dvXZDlZ8zFyQ_Xm'
    title: 'Deployment Planning'
    modifiedTime: '2020-02-27T19:24:49.947Z'
    version: 278
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'deployment-planning'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
