type: 'directory'
id: '1ZsKfca9jUrEMfvO-fEXf3_YY6984p04-'
title: 'Encounters'
fileName: 'encounters'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:07.422Z'
version: '119'
fileMap:
  preventive-care-set-up-and-documentation.bin:
    type: 'binary'
    id: '1NGmxMgaqtMykMtdSNTal26phaJmGFz2n'
    title: 'Preventive Care Set-Up & Documentation'
    modifiedTime: '2022-08-03T18:18:53.601Z'
    version: 1
    mimeType: 'application/vnd.google-apps.shortcut'
    fileName: 'preventive-care-set-up-and-documentation.bin'
  encounter-worklists.md:
    type: 'md'
    id: '1abTr620F-FY9LuKaPmqQomdsG1YOnha2ZSzP3PVcsQE'
    title: 'Encounter Worklists'
    modifiedTime: '2022-07-07T16:16:09.473Z'
    version: 51
    mimeType: 'text/x-markdown'
    lastAuthor: 'Bridget Hamm'
    fileName: 'encounter-worklists.md'
  encounter-protocols.md:
    type: 'md'
    id: '1hL-XtOsIVpllUcBoxAozZ3wHjQVhKU_Zz2oYxf92Zgg'
    title: 'Encounter Protocols'
    modifiedTime: '2022-02-14T18:53:42.540Z'
    version: 80
    mimeType: 'text/x-markdown'
    lastAuthor: 'Dawn Case'
    fileName: 'encounter-protocols.md'
  make-order-feature-encounter-plan-section.md:
    type: 'md'
    id: '1kEF-RWvZOJqe2pD7lr3XpwNbP73D0X8SXsRjGm4T-SA'
    title: 'Make Order Feature - Encounter Plan Section'
    modifiedTime: '2021-12-10T21:03:10.965Z'
    version: 132
    mimeType: 'text/x-markdown'
    lastAuthor: 'jlowrey'
    fileName: 'make-order-feature-encounter-plan-section.md'
  working-in-a-visit-encounter.md:
    type: 'md'
    id: '1lwIDrrDgkH3DGp6mHtl2HZdncjuCa-V4J31uanjRO4M'
    title: 'Working in a Visit Encounter'
    modifiedTime: '2021-12-06T16:40:10.096Z'
    version: 143
    mimeType: 'text/x-markdown'
    lastAuthor: 'jlowrey'
    fileName: 'working-in-a-visit-encounter.md'
  e-m-calculator.md:
    type: 'md'
    id: '1vx8LBCalWpRi7ldroS_qb4pD7m3CrJaS2ynbYMVu4kE'
    title: 'E/M Calculator'
    modifiedTime: '2021-08-30T16:38:08.151Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: 'sriecke'
    fileName: 'e-m-calculator.md'
  landingpages:
    type: 'directory'
    id: '1sNcirsE6P5DfHmJF1tOIk_Ibm7AQXlE-'
    title: 'landingpages'
    modifiedTime: '2021-02-26T15:53:52.343Z'
    version: 212
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'landingpages'
  telehealth.md:
    type: 'md'
    id: '1gqUkQvl5rLf5tbD0avlLfKSn0uy3tqcqqoY3U5XNQK8'
    title: 'TeleHealth'
    modifiedTime: '2020-03-31T14:31:43.227Z'
    version: 57
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'telehealth.md'
  encounter-plan-section-medications.md:
    type: 'md'
    id: '1sfvHUjlAN4xI1sXyPetceFUAPHYB9uko2GBdkKMys0A'
    title: 'Encounter Plan Section - Medications'
    modifiedTime: '2020-03-30T15:46:29.194Z'
    version: 124
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'encounter-plan-section-medications.md'
  encounters-labs-results-section.md:
    type: 'md'
    id: '14u88iIQ9MPABiJ1Yb_8gk0JYuSNf9m1GD0FPs1MQlp0'
    title: 'Encounters Labs Results Section'
    modifiedTime: '2020-03-26T17:39:27.991Z'
    version: 61
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'encounters-labs-results-section.md'
  working-in-a-legacy-encounter.md:
    type: 'md'
    id: '16OyfrWp_T5NN9--hJV0UYIuai2DYDU2v6COC3Gl0RYI'
    title: 'Working in a Legacy Encounter'
    modifiedTime: '2020-03-26T17:07:46.706Z'
    version: 90
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'working-in-a-legacy-encounter.md'
  telehealth:
    type: 'directory'
    id: '1CIvdAQPfRsjLtavjxAw_FWHO91hvMq3P'
    title: 'TeleHealth'
    modifiedTime: '2020-03-26T15:35:18.633Z'
    version: 291
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'telehealth'
  creating-or-adding-encounters.md:
    type: 'md'
    id: '1NUHcLxI6hYr5WaTyXHkQMxpA8UGjp2QsDnCnY5XgDvY'
    title: 'Creating or Adding Encounters'
    modifiedTime: '2020-03-13T15:01:30.440Z'
    version: 68
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'creating-or-adding-encounters.md'
  archiving-closing-re-archiving-encounters.md:
    type: 'md'
    id: '1ZGPm7WlJ13C8JXrlWdsWtqWnCt-cmbpsfooTKbEwQoo'
    title: 'Archiving/Closing/Re-archiving Encounters'
    modifiedTime: '2020-03-13T14:41:23.189Z'
    version: 58
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'archiving-closing-re-archiving-encounters.md'
  encounters-tab-search-and-list-view.md:
    type: 'md'
    id: '1M5Z8Y1w7SMPYZtQQ5EKbNqev5zTXSUfDu47E1Xt2I9A'
    title: 'Encounters Tab - Search and List View'
    modifiedTime: '2020-03-13T14:28:03.179Z'
    version: 60
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'encounters-tab-search-and-list-view.md'
  encounters-impression-section.md:
    type: 'md'
    id: '1cty4Ad6aB1dD-jT6ToDSxPtwxwM6LZt8PizcAGtrWXQ'
    title: 'Encounters Impression Section'
    modifiedTime: '2020-03-13T14:24:55.091Z'
    version: 48
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'encounters-impression-section.md'
  tests-and-procedures-section-applying-adding,-completing,-resulting.md:
    type: 'md'
    id: '1Ez2ziyzijOzWetkwbXonqkaJLt29prUDh4KTIApsbZA'
    title: 'Tests & Procedures Section - Applying/Adding, Completing, Resulting'
    modifiedTime: '2020-03-13T14:08:37.388Z'
    version: 126
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'tests-and-procedures-section-applying-adding,-completing,-resulting.md'
  tests-and-procedures-section-remove,-delete,-edit.md:
    type: 'md'
    id: '1noQHOYvPFVbNgLmHU-5MNMagJQNwAhyXxV_7XIuRz1E'
    title: 'Tests & Procedures Section - Remove, Delete, Edit'
    modifiedTime: '2020-02-27T21:14:57.599Z'
    version: 30
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'tests-and-procedures-section-remove,-delete,-edit.md'
  encounter-checkout-chart-tab.md:
    type: 'md'
    id: '16DqLuUFovyk-vCA4Y8_9iR1bfFfj4PsEXv8U59OzHKc'
    title: 'Encounter Checkout Chart Tab'
    modifiedTime: '2020-02-27T19:55:48.946Z'
    version: 40
    mimeType: 'text/x-markdown'
    fileName: 'encounter-checkout-chart-tab.md'
  encounter-summary-toolbar.md:
    type: 'md'
    id: '1clySsAxaHtCaH6Fbu2DkPG8tYBjFYeFj32WIa9oi3wI'
    title: 'Encounter Summary Toolbar'
    modifiedTime: '2020-02-27T19:55:26.253Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'encounter-summary-toolbar.md'
  work-related-exams.md:
    type: 'md'
    id: '15pWIFxaE93N1qz8om7mlP9CbHHTIpe3uFCLdB5FQeRg'
    title: 'Work-Related Exams'
    modifiedTime: '2020-02-27T19:52:48.211Z'
    version: 29
    mimeType: 'text/x-markdown'
    fileName: 'work-related-exams.md'
  dictation-and-transcription.md:
    type: 'md'
    id: '1jkkaykbJisElVA3anGLWgyfNIofH_SABJNTgiH2TMOY'
    title: 'Dictation and Transcription'
    modifiedTime: '2020-02-27T19:50:45.866Z'
    version: 35
    mimeType: 'text/x-markdown'
    fileName: 'dictation-and-transcription.md'
  work-related-exams:
    type: 'directory'
    id: '1jG_-SZfeYb-3g7gWGYBCjJoHObeVksKy'
    title: 'Work-Related Exams'
    modifiedTime: '2020-02-27T19:24:09.813Z'
    version: 310
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'work-related-exams'
  dictation-and-transcription:
    type: 'directory'
    id: '1yEDEyIAZGCOfAHqNAL1J9QQOUbmr6bU2'
    title: 'Dictation and Transcription'
    modifiedTime: '2020-02-27T19:24:08.310Z'
    version: 306
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'dictation-and-transcription'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
