type: 'directory'
id: '1kkI0MFLFMKd1y0GVy0oNI7xt1qNzoEds'
title: 'Measures'
fileName: 'measures'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:52.179Z'
version: '308'
fileMap:
  quality-measures-list.md:
    type: 'md'
    id: '14p6MPjeAHRsJuRApfeZpkbThZCc5BPl5jg_E5qwbG8Y'
    title: 'Quality Measures List'
    modifiedTime: '2022-04-29T13:27:40.204Z'
    version: 129
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'quality-measures-list.md'
  promoting-interoperability-pi-measures.md:
    type: 'md'
    id: '1jLnXdg6pwgBn2IHgzpTkWQjGwcN6WAcfE-8GY9CWfPw'
    title: 'Promoting Interoperability (PI) Measures'
    modifiedTime: '2020-02-28T21:58:39.683Z'
    version: 51
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'promoting-interoperability-pi-measures.md'
  improvement-activities-measures.md:
    type: 'md'
    id: '1B_0fEDI_OHFhhQBfVIAOuKo6RjXNWbt41gD2VCWHjKE'
    title: 'Improvement Activities Measures'
    modifiedTime: '2020-02-27T21:29:08.172Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'improvement-activities-measures.md'
  quality-measures-list:
    type: 'directory'
    id: '1QcK9EDNNfz8sjByQmnEWEgl-vobVNkaj'
    title: 'Quality Measures List'
    modifiedTime: '2020-02-27T19:25:02.117Z'
    version: 321
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'quality-measures-list'
  improvement-activities-measures:
    type: 'directory'
    id: '1zFKpUZmJhsD56st9CL56bPt1PSlaUHAn'
    title: 'Improvement Activities Measures'
    modifiedTime: '2020-02-27T19:24:54.975Z'
    version: 286
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'improvement-activities-measures'
  promoting-interoperability-pi-measures:
    type: 'directory'
    id: '175gOWUmjYeF7hCYkelVc9F4bgixAWDJD'
    title: 'Promoting Interoperability (PI) Measures'
    modifiedTime: '2020-02-27T19:24:53.269Z'
    version: 296
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'promoting-interoperability-pi-measures'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
