type: 'directory'
id: '19OVY8t3OzRAH8Ly5uYdIEoojjAFfRnz4'
title: 'Documents & Forms'
fileName: 'documents-and-forms'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:01.913Z'
version: '286'
fileMap:
  document-type-purge-rules.md:
    type: 'md'
    id: '1Ac4wN2_76DgVyWJwojqbeTzRDlcLPs18fcePYEADJRg'
    title: 'Document Type Purge Rules'
    modifiedTime: '2020-03-23T18:15:06.981Z'
    version: 58
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'document-type-purge-rules.md'
  link-documents-to-encounters.md:
    type: 'md'
    id: '1mcJnn30H7hx9cuQW4N201yIWBm0qMGI67jP-1R-UNgc'
    title: 'Link Documents to Encounters'
    modifiedTime: '2020-03-23T17:58:18.072Z'
    version: 78
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'link-documents-to-encounters.md'
  document-details.md:
    type: 'md'
    id: '1Wr-vTLd_jr5j2IcTTGKHlvQoD5bBdW0NolS-KrMK1cg'
    title: 'Document Details'
    modifiedTime: '2020-03-23T17:49:31.479Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'document-details.md'
  delete-move-lock-documents.md:
    type: 'md'
    id: '1uTO46APK2mbErCejVhXDlPSyVYOu3JHki92eUXmndz4'
    title: 'Delete/Move/Lock Documents'
    modifiedTime: '2020-03-23T17:21:07.161Z'
    version: 64
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'delete-move-lock-documents.md'
  form-documents.md:
    type: 'md'
    id: '1STg1IboQXC3rewUndw-9JrXgCW9svnyvZcdBbkrFBNU'
    title: 'Form Documents'
    modifiedTime: '2020-03-23T16:56:28.858Z'
    version: 87
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'form-documents.md'
  sketch-documents.md:
    type: 'md'
    id: '1S1X4Rn0y1DMGsQ1gFUmS7yLY4Tz8URodJsou-PVZxXM'
    title: 'Sketch Documents'
    modifiedTime: '2020-03-23T16:46:51.864Z'
    version: 72
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'sketch-documents.md'
  word-documents-cc-physicians-feature.md:
    type: 'md'
    id: '1C4Vw9cSEYMGiWWD7hKDjUEhxs2v4u8xyXKKN1BVJsLQ'
    title: 'Word Documents - CC Physicians Feature'
    modifiedTime: '2020-03-23T16:31:35.134Z'
    version: 76
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'word-documents-cc-physicians-feature.md'
  word-documents.md:
    type: 'md'
    id: '1bPHrMmurSq75UgvB6JHZ39n2FkPlQGrM9ZGQuhlYy1U'
    title: 'Word Documents'
    modifiedTime: '2020-03-23T16:26:17.055Z'
    version: 100
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'word-documents.md'
  add-document-legacy-view-vs.-current-view.md:
    type: 'md'
    id: '1dNxNSz-5WVkajvcEu_75ZhfFvTKftvREPAvop7CLRMc'
    title: 'Add Document - Legacy View vs. Current View'
    modifiedTime: '2020-03-20T21:16:25.996Z'
    version: 53
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'add-document-legacy-view-vs.-current-view.md'
  e-chart-scan-documents.md:
    type: 'md'
    id: '1uhZABnL3rktlj5EknE9RfqLdquq6eQFKknC-Dw8ZRLc'
    title: 'E-Chart Scan Documents'
    modifiedTime: '2020-03-09T19:33:19.747Z'
    version: 78
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'e-chart-scan-documents.md'
  x-ray-results-data-entry.md:
    type: 'md'
    id: '1MwxS6jLOhlJOif4APELiumSaoI0J-pRTX9W6zBZ3WtU'
    title: 'X-Ray Results Data Entry'
    modifiedTime: '2020-03-06T20:36:53.541Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'x-ray-results-data-entry.md'
  pft-data-entry.md:
    type: 'md'
    id: '1AaU-2q8717ibJc2q1igfSGQkhBf9D270y77vHQ_ITFg'
    title: 'PFT Data Entry'
    modifiedTime: '2020-03-06T20:35:16.544Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'pft-data-entry.md'
  ekg-data-entry.md:
    type: 'md'
    id: '1fPF1Dh5Vo8onrG7HPCr1mk69QGe43r8YvTiBy2V7WYY'
    title: 'EKG Data Entry'
    modifiedTime: '2020-03-06T20:29:53.003Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'ekg-data-entry.md'
  biometric-data-entry.md:
    type: 'md'
    id: '1-aDFfvOyr0OZIAvyKM5iXBaUFdNHRt6n5rYz4yXDFAs'
    title: 'Biometric Data Entry'
    modifiedTime: '2020-03-06T20:19:49.657Z'
    version: 41
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'biometric-data-entry.md'
  vision-data-entry.md:
    type: 'md'
    id: '15QkRlsqGLPA1PWa-dTVoLyRF4r4VI0keRhi3e_UtRFM'
    title: 'Vision Data Entry'
    modifiedTime: '2020-03-06T20:17:50.609Z'
    version: 59
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'vision-data-entry.md'
  audiogram-data-entry.md:
    type: 'md'
    id: '1uF8fI9QX3B_x4NeMoieH6XXnsJBHKRnaU1F_J-t99sA'
    title: 'Audiogram Data Entry'
    modifiedTime: '2020-03-06T20:14:35.197Z'
    version: 69
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'audiogram-data-entry.md'
  audio-vision-data-entry.md:
    type: 'md'
    id: '1_7hqvXyUU3mbM8rCJ8GvthD6asStMJ5d9pbZkBQv4FM'
    title: 'Audio-Vision Data Entry'
    modifiedTime: '2020-03-06T20:09:17.824Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'audio-vision-data-entry.md'
  bubble-forms.md:
    type: 'md'
    id: '1XuuEIvktT5TkE9GYEBduTnXgH40mjGyyCy_j7ElMAB0'
    title: 'Bubble Forms'
    modifiedTime: '2020-03-06T20:04:39.113Z'
    version: 45
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'bubble-forms.md'
  link-documents-to-order-requests.md:
    type: 'md'
    id: '1QPdP9x2P6JaMBy4iqaEYmhYlcHJjyRd0wdgXiVMGR2o'
    title: 'Link Documents to Order Requests'
    modifiedTime: '2020-03-06T17:48:39.034Z'
    version: 59
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'link-documents-to-order-requests.md'
  file-documents.md:
    type: 'md'
    id: '1PaBNyPuSASuXOWiDUToeTPjuyqzBrMI1qET5jEgLXKw'
    title: 'File Documents'
    modifiedTime: '2020-03-05T21:30:04.746Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'file-documents.md'
  picture-photo-documents.md:
    type: 'md'
    id: '1E5YYzxsfdGO75Ol__6jtjvnrteNioQ-QbT44hv1UqTY'
    title: 'Picture-Photo Documents'
    modifiedTime: '2020-03-05T20:49:06.831Z'
    version: 63
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'picture-photo-documents.md'
  pdf-documents.md:
    type: 'md'
    id: '153ycsbo_ev5FSulpz_r0YQPR1RqLO32JDVPuZagEuDY'
    title: 'PDF Documents'
    modifiedTime: '2020-03-05T20:46:46.117Z'
    version: 52
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'pdf-documents.md'
  text-documents.md:
    type: 'md'
    id: '1u7x_lyt-nR0_ZyRTOFwBilkSIkuoXLXqzNZuG_LC-Gc'
    title: 'Text Documents'
    modifiedTime: '2020-03-05T20:22:27.480Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'text-documents.md'
  link-documents-to-other-documents.md:
    type: 'md'
    id: '1kI4yQmijSxm-cGMcYMEs_emHoyOBOmF-3cEbYvJc4ak'
    title: 'Link Documents to Other Documents'
    modifiedTime: '2020-02-27T21:10:21.480Z'
    version: 64
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'link-documents-to-other-documents.md'
  adding-a-subject-to-documents.md:
    type: 'md'
    id: '1ajorGrYAiMAfEj9Fq7AF2UzhpuHuemMynqwiZunmvXk'
    title: 'Adding a Subject to Documents'
    modifiedTime: '2020-02-27T21:10:07.369Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'adding-a-subject-to-documents.md'
  document-properties.md:
    type: 'md'
    id: '1_uR3XH1DoBCrzV-nBO46Gq46zuqB1PBRe7-FYjGan4s'
    title: 'Document Properties'
    modifiedTime: '2020-02-27T21:10:00.312Z'
    version: 52
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'document-properties.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
