type: 'directory'
id: '1gq3BMLutr7wLSppoV4u0Ddcq_GelD5zX'
title: 'Financial functionality'
fileName: 'financial-functionality'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-02-17T14:41:33.228Z'
version: '229'
fileMap:
  editing-employer-organization-accounts.md:
    type: 'md'
    id: '1PzAcAguTcxDsfoxFIwdro80Mbtxql0QXRm45FBviNU8'
    title: 'Editing employer organization accounts'
    modifiedTime: '2021-03-02T19:33:32.499Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'editing-employer-organization-accounts.md'
  viewing-employer-organization-accounts.md:
    type: 'md'
    id: '1uSpG45pzytlu3fKcKN3qkVS_de74FqsYorRpcXXSONs'
    title: 'Viewing employer organization accounts'
    modifiedTime: '2021-03-02T19:33:30.808Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'viewing-employer-organization-accounts.md'
  printing-or-faxing-statements-or-creating-copies-on-optical-media.md:
    type: 'md'
    id: '1PA6EeczeCILKgQE0bBuWrU2YH7zp9tTrebyckzxkAyw'
    title: 'Printing or faxing statements or creating copies on optical media'
    modifiedTime: '2021-03-02T19:33:29.295Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'printing-or-faxing-statements-or-creating-copies-on-optical-media.md'
  removing-alert-comments-from-employer-organizations.md:
    type: 'md'
    id: '1YSZ1Ga02PL84P1G-aXE9I5RjrmjXctIFBilF4dJ0RH4'
    title: 'Removing alert comments from employer organizations'
    modifiedTime: '2021-02-22T16:24:03.440Z'
    version: 23
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'removing-alert-comments-from-employer-organizations.md'
  editing-alert-comments-of-employer-organizations.md:
    type: 'md'
    id: '16AgcK4vJ6iK8GaD6OvbIGeLya65G1r1YJrCH6C1mTWE'
    title: 'Editing alert comments of employer organizations'
    modifiedTime: '2021-02-22T16:15:41.376Z'
    version: 27
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'editing-alert-comments-of-employer-organizations.md'
  voiding-transactions.md:
    type: 'md'
    id: '1nNSmx2k5Ni0CUeTZQHLbeU3XDeHrhdZ9V2q6rh4jMWU'
    title: 'Voiding transactions'
    modifiedTime: '2021-02-18T19:12:24.594Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'voiding-transactions.md'
  viewing-financial-reports.md:
    type: 'md'
    id: '1Cj8xqTUIVxjRuCJPKOHbaYyKc2vdb-Rbm6NVzXHLX64'
    title: 'Viewing financial reports'
    modifiedTime: '2021-02-18T19:11:41.072Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'viewing-financial-reports.md'
  viewing-cleared,-flagged,-or-reconciled-transactions.md:
    type: 'md'
    id: '1yGFA_7iHZBY2hTo4OadZcZE_EyZmN_6Om4XgLZZPudI'
    title: 'Viewing cleared, flagged, or reconciled transactions'
    modifiedTime: '2021-02-18T19:10:40.416Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'viewing-cleared,-flagged,-or-reconciled-transactions.md'
  using-information-about-expired-fee-schedules-in-grids.md:
    type: 'md'
    id: '1p7wZkQtojxLvxtFtLCsGHUlWBFkAgh3Mxay-pZ3sws4'
    title: 'Using information about expired fee schedules in grids'
    modifiedTime: '2021-02-18T19:10:05.187Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'using-information-about-expired-fee-schedules-in-grids.md'
  viewing-expired-fee-schedules.md:
    type: 'md'
    id: '13Vqoc-fzNNDUkmHn6m-JNdEv9i0jiTh96DmBiJD1TW8'
    title: 'Viewing expired fee schedules'
    modifiedTime: '2021-02-18T19:09:23.465Z'
    version: 23
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'viewing-expired-fee-schedules.md'
  updating-transactions.md:
    type: 'md'
    id: '1Ue6lNKwOnv04L49jydrvYRs2xIHXHp8cmIA6WdCoCVM'
    title: 'Updating transactions'
    modifiedTime: '2021-02-18T19:06:46.993Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'updating-transactions.md'
  removing-fee-schedule-items.md:
    type: 'md'
    id: '187UVX4E-pSGk_vuUSTIVtKyQ5TrmNSUdUKlCumYEb70'
    title: 'Removing fee schedule items'
    modifiedTime: '2021-02-18T19:05:40.442Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'removing-fee-schedule-items.md'
  removing-employees-from-employer-organizations.md:
    type: 'md'
    id: '1jTjf5dzqvReObpzAIGWWv94YQnJVu8EE45xUmPdU-rg'
    title: 'Removing employees from employer organizations'
    modifiedTime: '2021-02-18T19:04:36.030Z'
    version: 23
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'removing-employees-from-employer-organizations.md'
  printing-information-about-expired-fee-schedules.md:
    type: 'md'
    id: '1NM21bUDsEVAbMZ-hJ4USGD5OqjUAbosvbnKr_HbA44s'
    title: 'Printing information about expired fee schedules'
    modifiedTime: '2021-02-18T18:55:24.956Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'printing-information-about-expired-fee-schedules.md'
  ledger.md:
    type: 'md'
    id: '1TAzMICd2BvvJW5UQAB0sYb8ey1_ni3MS5Sc5neKFysg'
    title: 'Ledger'
    modifiedTime: '2021-02-18T17:00:30.156Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'ledger.md'
  indicating-employer-preferred-statement-delivery-method.md:
    type: 'md'
    id: '1CSjIPGRdMMT6Z8bVhH_-x-x015LUHKZBjf2TLFZbesc'
    title: 'Indicating employer-preferred statement delivery method'
    modifiedTime: '2021-02-18T16:48:19.492Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'indicating-employer-preferred-statement-delivery-method.md'
  finding-ledger-transactions.md:
    type: 'md'
    id: '1-tfONkRUSjg4mxAfE1pcRYwgRK2t1LN-Vw9qorSz9U8'
    title: 'Finding ledger transactions'
    modifiedTime: '2021-02-18T16:48:01.963Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'finding-ledger-transactions.md'
  exporting-information-about-expired-fee-schedules.md:
    type: 'md'
    id: '1jVx-TyKaSysXg-bHQxx-s-rUXXdPST_m4N2xs69HJNw'
    title: "Exporting information about expired fee schedules\_"
    modifiedTime: '2021-02-18T16:47:05.726Z'
    version: 15
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'exporting-information-about-expired-fee-schedules.md'
  editing-fee-schedules.md:
    type: 'md'
    id: '10aFlpPIgkByaCg8guomuqePXoYKDHBsz0GmnfrFxIUA'
    title: 'Editing Fee Schedules'
    modifiedTime: '2021-02-18T16:46:34.672Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'editing-fee-schedules.md'
  editing-fee-schedule-items.md:
    type: 'md'
    id: '1cpxFuKA3udQG8pkj7pt_2RjASRslJiyB4hnn-5m_QK0'
    title: 'Editing fee schedule items'
    modifiedTime: '2021-02-18T16:23:00.915Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'editing-fee-schedule-items.md'
  editing-employer-organization-contacts.md:
    type: 'md'
    id: '1kshWUcFrvmzCRJ9LGkoDz6WRXkLMRJigN7IBjrv11sE'
    title: 'Editing employer organization contacts'
    modifiedTime: '2021-02-18T16:22:14.232Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'editing-employer-organization-contacts.md'
  duplicating-fee-schedules.md:
    type: 'md'
    id: '14vLHPlYfqemFhoLO8lssEsb-0UjUSXtwfD9J8M2uxg4'
    title: 'Duplicating fee schedules'
    modifiedTime: '2021-02-18T16:21:40.612Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'duplicating-fee-schedules.md'
  downloading-financial-reports.md:
    type: 'md'
    id: '1Qn_UKkXBXlhhXIgIOUvawMwUyEaqE5uAB1Vq_5rOe1Y'
    title: 'Downloading financial reports'
    modifiedTime: '2021-02-18T16:20:52.868Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'downloading-financial-reports.md'
  creating-statements.md:
    type: 'md'
    id: '1guBfPHlZtquQes746UnDcPSNkBLRH5v9ZygrzIQtl98'
    title: 'Creating Statements'
    modifiedTime: '2021-02-18T16:19:45.481Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'creating-statements.md'
  creating-employer-organizations.md:
    type: 'md'
    id: '1E2Ng93ephPTQ3exGsMiJs2_m51ZhI-uWMW3UJlk1rYQ'
    title: 'Creating employer organizations'
    modifiedTime: '2021-02-18T16:07:46.271Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'creating-employer-organizations.md'
  creating-and-adding-employees-to-employer-organizations.md:
    type: 'md'
    id: '1CAZjCsB94t6Ygi1zrtOPb4q7Um23HyMO-rx7zW8T9BQ'
    title: 'Creating and adding employees to employer organizations'
    modifiedTime: '2021-02-18T16:06:30.420Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'creating-and-adding-employees-to-employer-organizations.md'
  creating-and-adding-accounts-to-employer-organizations.md:
    type: 'md'
    id: '1BiAg3NNKItfczDawRTAiRmzjL7LyiE3AKSdrfQLTXR0'
    title: 'Creating and adding accounts to employer organizations'
    modifiedTime: '2021-02-18T16:05:37.475Z'
    version: 24
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'creating-and-adding-accounts-to-employer-organizations.md'
  configuring-access-to-prices.md:
    type: 'md'
    id: '1lBr46ADVjyFfGmtfJEHgiTOSGxzYKZ2wQtjcGN-DOm8'
    title: 'Configuring access to prices'
    modifiedTime: '2021-02-18T16:00:00.468Z'
    version: 15
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'configuring-access-to-prices.md'
  configuring-access-to-ledger.md:
    type: 'md'
    id: '16mRc8J0pBrOwb2iPNF4WzPxSkPCkqj0XzH_iZORsJco'
    title: 'Configuring access to ledger'
    modifiedTime: '2021-02-18T15:53:28.874Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'configuring-access-to-ledger.md'
  configuring-access-to-financial-modifiers.md:
    type: 'md'
    id: '11AXz_kKVW3chcUj1EQ0SW4xZKQWtUMjpRpXhs4e9a40'
    title: 'Configuring access to financial modifiers'
    modifiedTime: '2021-02-18T15:53:02.660Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'configuring-access-to-financial-modifiers.md'
  configuring-access-to-financial-funding-sources.md:
    type: 'md'
    id: '1Nk51k7eFk7sbCADxwOlfsWb4sxLGdc6kkva5tWhS1GU'
    title: 'Configuring access to financial funding sources'
    modifiedTime: '2021-02-18T15:52:51.275Z'
    version: 15
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'configuring-access-to-financial-funding-sources.md'
  configuring-access-to-encounter-charges.md:
    type: 'md'
    id: '1ZOGOaZqB2_SoMwy14nI5Z4C2Ih3Fi1j0GG6A6KHL_vM'
    title: "Configuring access to encounter charges\_"
    modifiedTime: '2021-02-18T15:52:33.084Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'configuring-access-to-encounter-charges.md'
  closing-and-posting-transactions.md:
    type: 'md'
    id: '1HRu6JJaf7bNjxyg4u0saJ5lNnc338GczKp_pS00cNts'
    title: 'Closing and posting transactions'
    modifiedTime: '2021-02-17T23:34:03.855Z'
    version: 25
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'closing-and-posting-transactions.md'
  changing-status-of-transactions.md:
    type: 'md'
    id: '1pISPoaGjFEUXJIn4L596IzcvvNexhYS3IoxcKs1hBxU'
    title: 'Changing status of transactions'
    modifiedTime: '2021-02-17T22:55:00.202Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'changing-status-of-transactions.md'
  changing-organizations-to-employer-organizations.md:
    type: 'md'
    id: '1t47yFVdezErENnyK84PHViNVEbTChtzcTMiUkZY_0eg'
    title: 'Changing organizations to employer organizations'
    modifiedTime: '2021-02-17T22:50:42.522Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'changing-organizations-to-employer-organizations.md'
  changing-ledger-views.md:
    type: 'md'
    id: '1Mwnmcg-Lvz8wiRmN-NaXvKaKhLlAzK-kSKlDPjRp2a0'
    title: 'Changing ledger views'
    modifiedTime: '2021-02-17T22:50:16.684Z'
    version: 18
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'changing-ledger-views.md'
  applying-self-payments.md:
    type: 'md'
    id: '1B7Df4vCyxBjC_iv5DUyiHU8fdRWlxsjp5OTx-D0W6YY'
    title: 'Applying self payments'
    modifiedTime: '2021-02-17T22:48:31.800Z'
    version: 25
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'applying-self-payments.md'
  adding-transactions-to-the-ledger.md:
    type: 'md'
    id: '1VuohA2vzHB3mq7i4j-79u8d7CF6ZUDi5LtoUhM0w5Yk'
    title: 'Adding transactions to the ledger'
    modifiedTime: '2021-02-17T22:46:14.361Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-transactions-to-the-ledger.md'
  adding-items-to-fee-schedules.md:
    type: 'md'
    id: '1cOmkqlSjVkfZtpNOOYSyGMM6K3pE26qzEDVZXOeM04M'
    title: 'Adding items to fee schedules'
    modifiedTime: '2021-02-17T22:45:32.263Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-items-to-fee-schedules.md'
  adding-existing-patients-as-employees-of-employer-organizations.md:
    type: 'md'
    id: '12J14BKaX9AZmKKDENDSoHs1Q7OYIdjQFYumYezwOn2Y'
    title: 'Adding existing patients as employees of employer organizations'
    modifiedTime: '2021-02-17T22:42:29.145Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-existing-patients-as-employees-of-employer-organizations.md'
  adding-existing-employer-organizations-as-subordinates-to-employer-organizations.md:
    type: 'md'
    id: '1AWtRR0K-hVwnz27RBadPBBgzQUk4CC-thrR1nxVc1zI'
    title: 'Adding existing employer organizations as subordinates to employer organizations'
    modifiedTime: '2021-02-17T22:42:13.835Z'
    version: 15
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-existing-employer-organizations-as-subordinates-to-employer-organizations.md'
  adding-deals.md:
    type: 'md'
    id: '1RwavD1Q59PIs4xjzk_RJp_T9Wl8d-p65Lq7gOPM6sGU'
    title: 'Adding deals'
    modifiedTime: '2021-02-17T22:41:51.144Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-deals.md'
  adding-contacts-to-employer-organizations.md:
    type: 'md'
    id: '1rRzAtW7BfU-8WHT-qdKZGpojZkxbBuPQAxO4jCEfoFA'
    title: 'Adding contacts to employer organizations'
    modifiedTime: '2021-02-17T22:24:33.565Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-contacts-to-employer-organizations.md'
  adding-alert-comments-to-employer-organizations.md:
    type: 'md'
    id: '1vV9ZAwk3eHys6SHAKLCBXPZpgiiuyilqQHifr7OEPkk'
    title: 'Adding alert comments to employer organizations'
    modifiedTime: '2021-02-17T22:23:31.889Z'
    version: 26
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'adding-alert-comments-to-employer-organizations.md'
  accessing-the-ledger.md:
    type: 'md'
    id: '1gJHX6m5_tSU6dDiKs7HAH3Qxjad1wSNRUtHsDHBW8Ew'
    title: 'Accessing the ledger'
    modifiedTime: '2021-02-17T22:23:12.576Z'
    version: 28
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'accessing-the-ledger.md'
  editing-employer-organizations.md:
    type: 'md'
    id: '1PleeV1Z7fxATGu1yowdD2s_fPffeoRkLVlFzNyCYPQw'
    title: 'Editing employer organizations'
    modifiedTime: '2021-02-17T19:45:31.248Z'
    version: 16
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'editing-employer-organizations.md'
  configuring-security-access-to-financial-functionality.md:
    type: 'md'
    id: '1cgHitbsGGsBCtSaH5CsbHIPK9r9TXE8Bv746Xzk6mZ0'
    title: 'Configuring security access to financial functionality'
    modifiedTime: '2021-02-17T19:44:58.716Z'
    version: 14
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'configuring-security-access-to-financial-functionality.md'
  viewing-all-fee-schedules.md:
    type: 'md'
    id: '1nad6bnJlNKZcV7TI6aSKIG4J2twAgP_Damj7nU-nGkI'
    title: 'Viewing all fee schedules'
    modifiedTime: '2021-02-17T19:43:21.908Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'viewing-all-fee-schedules.md'
  finding-fee-schedules.md:
    type: 'md'
    id: '1SibGIGvDkzE-S2ExN9dD5S_HuOEN5xtJqZNNliLNE_s'
    title: 'Finding fee schedules'
    modifiedTime: '2021-02-17T19:43:17.825Z'
    version: 21
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'finding-fee-schedules.md'
  creating-fee-schedules.md:
    type: 'md'
    id: '1_QeV-kfz9yuYUbv_npFVZ4_lnZQTj3UgRZRG8mbJsKw'
    title: 'Creating fee schedules'
    modifiedTime: '2021-02-17T19:43:13.773Z'
    version: 16
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'creating-fee-schedules.md'
  fee-schedules.md:
    type: 'md'
    id: '1sSy0HOZEuSlpQCX9UsAovxKI3N28tC7H6jI8xqIHfHE'
    title: 'Fee  schedules'
    modifiedTime: '2021-02-17T19:43:08.754Z'
    version: 13
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'fee-schedules.md'
  financial-reports.md:
    type: 'md'
    id: '1iFRS0IzYxv4R7Apt3ypVwM_P7t6vY0ndnG6DxJTAkwQ'
    title: 'Financial reports'
    modifiedTime: '2021-02-17T19:42:45.858Z'
    version: 14
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'financial-reports.md'
  finding-employer-organizations.md:
    type: 'md'
    id: '1Al_53cJIgXetnbNLD0FLUXjIy7Gul0aHAPQJGPHwNdg'
    title: 'Finding employer organizations'
    modifiedTime: '2021-02-17T19:42:19.484Z'
    version: 16
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'finding-employer-organizations.md'
  employer-organizations.md:
    type: 'md'
    id: '1zUjSH1KBHMY85zmq6vRGN39Lir2X3K4RMjXq6UgGBvI'
    title: 'Employer organizations'
    modifiedTime: '2021-02-17T19:42:15.067Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'employer-organizations.md'
  deals.md:
    type: 'md'
    id: '1GGqEjpljaHjSu1ZhgbJJdh1aPJY8q2Pb8gBAPQJH-hI'
    title: 'Deals'
    modifiedTime: '2021-02-17T19:42:06.794Z'
    version: 14
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'deals.md'
  financial-functionality.md:
    type: 'md'
    id: '1nh4HHOr1akWGgol1SR1uC4beRIMW1yEk4pBa-nGMBn0'
    title: 'Financial functionality'
    modifiedTime: '2021-02-17T19:42:03.299Z'
    version: 12
    mimeType: 'text/x-markdown'
    lastAuthor: 'ahumes'
    fileName: 'financial-functionality.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
