type: 'directory'
id: '1i4kSmWAUFrEIyYF038E2G1w-plZTiJR-'
title: 'Injury Care'
fileName: 'injury-care'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:10.809Z'
version: '21'
fileMap:
  work-status.md:
    type: 'md'
    id: '1EuB61nCaNeWo6leAxOJQb9kK8Vqqhba95SNwjTa-6_0'
    title: 'Work Status'
    modifiedTime: '2022-02-28T13:19:38.720Z'
    version: 74
    mimeType: 'text/x-markdown'
    lastAuthor: 'sriecke'
    fileName: 'work-status.md'
  adding-restrictions-and-accommodations.md:
    type: 'md'
    id: '1iIBBj7YhPN--toi1eztojxqRu70YpPCulg8vowFjRlg'
    title: 'Adding Restrictions and Accommodations'
    modifiedTime: '2022-01-04T12:03:57.110Z'
    version: 96
    mimeType: 'text/x-markdown'
    lastAuthor: 'Angie Nichols'
    fileName: 'adding-restrictions-and-accommodations.md'
  editing-restriction-types.md:
    type: 'md'
    id: '1CP3XnZGIC393d5tXYOAFsDa_IO-Am7l_OqY8N1U5sLE'
    title: 'Editing Restriction Types'
    modifiedTime: '2020-03-30T16:34:03.981Z'
    version: 93
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'editing-restriction-types.md'
  viewing-restrictions-and-accommodations.md:
    type: 'md'
    id: '1YCVJuiM8IJKCQ2Rk0_m1NCJ2IwJ4-EEbQZyz_A7vW9A'
    title: 'Viewing Restrictions and Accommodations'
    modifiedTime: '2020-03-13T11:46:45.933Z'
    version: 49
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'viewing-restrictions-and-accommodations.md'
  case-management.md:
    type: 'md'
    id: '16-7poNmo_A35wJg_Sxb-bc-fbNHrEfSfMrlJjzpvmq8'
    title: 'Case Management'
    modifiedTime: '2020-02-27T19:30:41.423Z'
    version: 23
    mimeType: 'text/x-markdown'
    fileName: 'case-management.md'
  case-management:
    type: 'directory'
    id: '1OX4OmJq4Lv_5g8mLjfb-U-tzJldgqeH2'
    title: 'Case Management'
    modifiedTime: '2020-02-27T19:25:01.248Z'
    version: 304
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'case-management'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
