type: 'directory'
id: '1-igmW4ma-gS62gDOsYThI1wL_Hbqrxso'
title: 'System Configuration'
fileName: 'system-configuration'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:59.133Z'
version: '110'
fileMap:
  encounters-protocol-configuration-and-programming.md:
    type: 'md'
    id: '19b7c8803bKvIhulmLIHQnmOG8v8sQsWfj-jLEN4jgOY'
    title: 'Encounters Protocol Configuration & Programming'
    modifiedTime: '2021-12-08T15:28:41.216Z'
    version: 169
    mimeType: 'text/x-markdown'
    lastAuthor: 'jlowrey'
    fileName: 'encounters-protocol-configuration-and-programming.md'
  chart-tabs.md:
    type: 'md'
    id: '1152N8SuEFh-XXf0Rev0oGdD4ErLhyvoG5eFGYhcOtOk'
    title: 'Chart Tabs'
    modifiedTime: '2021-07-22T14:52:57.002Z'
    version: 140
    mimeType: 'text/x-markdown'
    lastAuthor: 'Bridget Hamm'
    fileName: 'chart-tabs.md'
  system-files-management.md:
    type: 'md'
    id: '1faeAEwfFOMCYV4zh0yko4gGtLwhgypG1ZtcSZXAbAn4'
    title: 'System Files Management'
    modifiedTime: '2020-03-20T20:50:43.774Z'
    version: 71
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'system-files-management.md'
  document-type-tab.md:
    type: 'md'
    id: '1cKcHC0ShLX-AyNro4x-3zsZefccwS3im2LletR2x__Q'
    title: 'Document Type Tab'
    modifiedTime: '2020-03-20T20:37:35.642Z'
    version: 91
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'document-type-tab.md'
  chart-types-editor.md:
    type: 'md'
    id: '1QZKVqleCbfau8qypHvxece9sleS3_E2WJcQTQRCuLgE'
    title: 'Chart Types Editor'
    modifiedTime: '2020-03-20T17:54:38.850Z'
    version: 73
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'chart-types-editor.md'
  autocomplete-editor.md:
    type: 'md'
    id: '1gf_5k9tQYpPKSQ0upiD07Sjk76Kulne3EvseAf6VOe8'
    title: 'Autocomplete Editor'
    modifiedTime: '2020-03-05T17:46:48.962Z'
    version: 45
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'autocomplete-editor.md'
  side-chart-configuration.md:
    type: 'md'
    id: '1MA8AzNlicKyg00XYAgsnYL-jDg0tk6nQ0Sb0TjTVkng'
    title: 'Side Chart Configuration'
    modifiedTime: '2020-03-05T17:32:44.289Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'side-chart-configuration.md'
  locations-manager-tab.md:
    type: 'md'
    id: '1FcMVfuPF7b2-6-WkhSYxOaWUogJP5h9cWhLvtWLYDFw'
    title: 'Locations Manager Tab'
    modifiedTime: '2020-03-05T17:14:42.915Z'
    version: 49
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'locations-manager-tab.md'
  locations-management.md:
    type: 'md'
    id: '1NXuzy5Hqh0rQYLV1ldqUyIGNbiLMjiN-sYTjt2fUcYs'
    title: 'Locations Management'
    modifiedTime: '2020-03-05T17:06:16.370Z'
    version: 76
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'locations-management.md'
  fee-schedules.md:
    type: 'md'
    id: '1UN8pMffETbIAzX3R9mA86EeIp_XG0joWzFDs0tC9eto'
    title: 'Fee Schedules'
    modifiedTime: '2020-02-27T19:34:17.779Z'
    version: 54
    mimeType: 'text/x-markdown'
    fileName: 'fee-schedules.md'
  managing-departments.md:
    type: 'md'
    id: '1FVIc0ethQ9im8Nf1LfxHlcEkQ-hIR8YPlHZbNHxzHm0'
    title: 'Managing Departments'
    modifiedTime: '2020-02-27T19:33:06.713Z'
    version: 45
    mimeType: 'text/x-markdown'
    fileName: 'managing-departments.md'
  work-locations-tab-work-regions.md:
    type: 'md'
    id: '15E6hML4fxFd1XvQEpRfClxdjy4YQ97I3KB89XBc_Rfc'
    title: 'Work Locations Tab - Work Regions'
    modifiedTime: '2020-02-27T19:32:54.120Z'
    version: 57
    mimeType: 'text/x-markdown'
    fileName: 'work-locations-tab-work-regions.md'
  colors.md:
    type: 'md'
    id: '1c_NR6b7WnKmTXG3LmEy2jwpnNK2a007XE4igVcNLOzA'
    title: 'Colors'
    modifiedTime: '2020-02-27T19:32:06.134Z'
    version: 115
    mimeType: 'text/x-markdown'
    fileName: 'colors.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
