type: 'directory'
id: '1TdezD8IpvdAghiYsIKx-IZ2N-w_9AcsL'
title: 'Visit Encounter'
fileName: 'visit-encounter'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-02-23T20:26:07.925Z'
version: '11'
fileMap: {}
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
