type: 'directory'
id: '1uWsxZgKQn5wnb5Wa81Y4xDUvFsa02rBf'
title: 'FHIR Application Programming Interface (API)'
fileName: 'fhir-application-programming-interface-api'
mimeType: 'application/vnd.google-apps.folder'
date: '2022-07-26T17:07:34.356Z'
version: '25'
fileMap:
  oauth-2.0-tutorial.md:
    type: 'md'
    id: '1y6n0lw4prz4Rg_7HKbhcgPN6p9y4wNa5m2dw4rr9Tfk'
    title: 'OAuth 2.0 Tutorial'
    modifiedTime: '2022-08-11T20:55:18.853Z'
    version: 293
    mimeType: 'text/x-markdown'
    lastAuthor: 'Grzegorz Godlewski'
    fileName: 'oauth-2.0-tutorial.md'
  resource-specifications.md:
    type: 'md'
    id: '1pra9Trk_pf9pWs5HVMcFyq8rC3ubybUPZ0_Il2M3uoE'
    title: 'Resource Specifications'
    modifiedTime: '2022-08-08T21:10:35.978Z'
    version: 491
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'resource-specifications.md'
  terms-of-use.md:
    type: 'md'
    id: '1e3kmiavTOjCuKHwE8uz4Ucyr1tNyN3CYJrKYgFN-rec'
    title: 'Terms of Use'
    modifiedTime: '2022-08-03T13:59:57.646Z'
    version: 81
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'terms-of-use.md'
  endpoints.md:
    type: 'md'
    id: '1R6Ge6G2HJm4KVoyKIdvSLBVhl_GpRie7SMiic5j426U'
    title: 'Endpoints'
    modifiedTime: '2022-08-03T13:55:34.734Z'
    version: 24
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'endpoints.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
