type: 'directory'
id: '1uWsxZgKQn5wnb5Wa81Y4xDUvFsa02rBf'
title: 'FHIR Application Programming Interface (API)'
fileName: 'fhir-application-programming-interface-api'
mimeType: 'application/vnd.google-apps.folder'
date: '2022-07-26T17:07:34.356Z'
version: '25'
fileMap:
  resource-specifications.md:
    type: 'md'
    id: '1pra9Trk_pf9pWs5HVMcFyq8rC3ubybUPZ0_Il2M3uoE'
    title: 'Resource Specifications'
    modifiedTime: '2022-08-30T15:25:37.584Z'
    version: 498
    mimeType: 'text/x-markdown'
    lastAuthor: 'Will Reiske'
    fileName: 'resource-specifications.md'
  oauth-2.0-tutorial.md:
    type: 'md'
    id: '1y6n0lw4prz4Rg_7HKbhcgPN6p9y4wNa5m2dw4rr9Tfk'
    title: 'OAuth 2.0 Tutorial'
    modifiedTime: '2022-08-27T05:26:22.579Z'
    version: 302
    mimeType: 'text/x-markdown'
    lastAuthor: 'Will Reiske'
    fileName: 'oauth-2.0-tutorial.md'
  terms-of-use.md:
    type: 'md'
    id: '1e3kmiavTOjCuKHwE8uz4Ucyr1tNyN3CYJrKYgFN-rec'
    title: 'Terms of Use'
    modifiedTime: '2022-08-03T13:59:57.646Z'
    version: 81
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'terms-of-use.md'
  endpoints.md:
    type: 'md'
    id: '1R6Ge6G2HJm4KVoyKIdvSLBVhl_GpRie7SMiic5j426U'
    title: 'Endpoints'
    modifiedTime: '2022-08-03T13:55:34.734Z'
    version: 24
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'endpoints.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
