type: 'directory'
id: '1vvPtXtsHlz61luI3a7NTjPhvSWgnXUcF'
title: 'Health Surveillance'
fileName: 'health-surveillance'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:11.837Z'
version: '301'
fileMap:
  health-surveillance-playbook.md:
    type: 'md'
    id: '1NCyrhUd_Qk586gaah_GvEGedpBOkizQteEtPsldw4C4'
    title: 'Health Surveillance Playbook'
    modifiedTime: '2022-03-21T21:33:08.544Z'
    version: 256
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'health-surveillance-playbook.md'
  health-surveillance-matrix.md:
    type: 'md'
    id: '1uE3JqvyP8KAbK2mO0sIrGUZa32BhgHULC3NdSyakf4M'
    title: 'Health Surveillance Matrix'
    modifiedTime: '2022-03-21T21:30:48.363Z'
    version: 54
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'health-surveillance-matrix.md'
  due-list.md:
    type: 'md'
    id: '1K5UaYbMQfk8hO8SLpWlUDIEsm3-u6zYdENSWRY2Usdg'
    title: 'Due List'
    modifiedTime: '2020-03-30T17:02:56.352Z'
    version: 83
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'due-list.md'
  panel-action-evaluator.md:
    type: 'md'
    id: '1pLP-8271fYi3d0yBZp8dKaZbvqpMs-aIpwLzjhC5L6g'
    title: 'Panel Action Evaluator'
    modifiedTime: '2020-03-13T15:20:58.197Z'
    version: 54
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'panel-action-evaluator.md'
  health-surveillance-panels-action-rules.md:
    type: 'md'
    id: '10wTqIF8gtUDBbJmbk_LjlUeNmtU_vvbVFoVWTZnuMqc'
    title: 'Health Surveillance Panels - Action Rules'
    modifiedTime: '2020-03-13T15:15:41.577Z'
    version: 56
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'health-surveillance-panels-action-rules.md'
  health-surveillance-panels-actions.md:
    type: 'md'
    id: '1OT1DksCGhaN10pyrC0PsDh5DAj7IDhSAFsgANe0Ru54'
    title: 'Health Surveillance Panels - Actions'
    modifiedTime: '2020-03-13T15:11:36.505Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'health-surveillance-panels-actions.md'
  introduction-to-health-surveillance-panels.md:
    type: 'md'
    id: '1IPkv7nQyNjg2KisIdIAJUuoJfUF6Le7iK5-HHq6ssik'
    title: 'Introduction to Health Surveillance Panels'
    modifiedTime: '2020-03-13T15:08:54.014Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'introduction-to-health-surveillance-panels.md'
  respirator-info-chart-tab.md:
    type: 'md'
    id: '1hC2eNGlT7-hlJL8e0UtDCtFdjzHuswjFqxryMOzc8zU'
    title: 'Respirator Info Chart Tab'
    modifiedTime: '2020-02-27T20:00:56.891Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'respirator-info-chart-tab.md'
  due-list-in-a-dynamic-encounter.md:
    type: 'md'
    id: '1NHVGEeKbx_wGt0Y8K3WXwos-rv3dRUg4Ev6n7tdTD1Y'
    title: 'Due List in a Dynamic Encounter'
    modifiedTime: '2020-02-27T20:00:48.718Z'
    version: 51
    mimeType: 'text/x-markdown'
    fileName: 'due-list-in-a-dynamic-encounter.md'
  viewing-health-surveillance-panels-and-membership.md:
    type: 'md'
    id: '1CuNALp11tyFSx3IKXsJNA7IO-lGT-ZA2PQi8AOKKfxM'
    title: 'Viewing Health Surveillance Panels & Membership'
    modifiedTime: '2020-02-27T20:00:28.475Z'
    version: 37
    mimeType: 'text/x-markdown'
    fileName: 'viewing-health-surveillance-panels-and-membership.md'
  health-surveillance-panels-automated-membership.md:
    type: 'md'
    id: '1jZ5PGqbKCzAKcaFR6idH4tUAWnft-WvzAcuJY4pDj1I'
    title: 'Health Surveillance Panels - Automated Membership'
    modifiedTime: '2020-02-27T20:00:00.803Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'health-surveillance-panels-automated-membership.md'
  health-surveillance-panels-add-memberships-manually.md:
    type: 'md'
    id: '1TBgwfsvuA6mkom7js7uw9tJJspLucwitVAfs-WC0VPA'
    title: 'Health Surveillance Panels - Add Memberships Manually'
    modifiedTime: '2020-02-27T19:59:52.225Z'
    version: 29
    mimeType: 'text/x-markdown'
    fileName: 'health-surveillance-panels-add-memberships-manually.md'
  adding-editing-health-surveillance-panels.md:
    type: 'md'
    id: '1YPGoGXS1qbrFdUO-FfDCLr0ln_li24Xw8Zdx0u53BnM'
    title: 'Adding/Editing Health Surveillance Panels'
    modifiedTime: '2020-02-27T19:59:26.235Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'adding-editing-health-surveillance-panels.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
