type: 'directory'
id: '1JfLUoDMo5-befWCXvGO6dGVqYnChxtVN'
title: 'Reports'
fileName: 'reports'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:19.177Z'
version: '280'
fileMap:
  guideline-report.md:
    type: 'md'
    id: '1RWPdiF4m082Uy3ENvU-4lRS_edV78dltrktYW6cA70s'
    title: 'Guideline Report'
    modifiedTime: '2021-12-03T16:46:47.430Z'
    version: 32
    mimeType: 'text/x-markdown'
    lastAuthor: 'Bridget Hamm'
    fileName: 'guideline-report.md'
  transcription-report.md:
    type: 'md'
    id: '1bTJ6VujPQavXt-wY3eUY2U9Q2hqrlw1Mu59Aasd0OfM'
    title: 'Transcription Report'
    modifiedTime: '2021-02-22T18:34:34.162Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: 'egrzetich'
    fileName: 'transcription-report.md'
  to-restrict-report-access.md:
    type: 'md'
    id: '1GYFmbEH6_WAX9FHm6nAfTpxTCeVvx5NVvpAh1ZNdkUg'
    title: 'To Restrict Report Access'
    modifiedTime: '2020-03-16T16:58:57.557Z'
    version: 47
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'to-restrict-report-access.md'
  documents-report-super-document-type-search.md:
    type: 'md'
    id: '1KfyrlzPYLJ6uPSz-YQlVG15nEQyn6URH5izKL20GRJ0'
    title: 'Documents Report / Super Document Type Search'
    modifiedTime: '2020-03-16T16:41:16.740Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'documents-report-super-document-type-search.md'
  demographics-report.md:
    type: 'md'
    id: '1xV8LjYenQ4Ypmbno3hav_Iz_VNKt2q_ZUhuf-iV1FUg'
    title: 'Demographics Report'
    modifiedTime: '2020-03-16T16:39:56.253Z'
    version: 35
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'demographics-report.md'
  checkin-reports.md:
    type: 'md'
    id: '1wiiDtA6Dlmbqe65Sx1tJh-cDj-Ld7D5GmICs6-qXoNU'
    title: 'Checkin Reports'
    modifiedTime: '2020-03-16T16:36:21.421Z'
    version: 32
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'checkin-reports.md'
  using-datavis-grids-data-tools.md:
    type: 'md'
    id: '1Ghj2RP8IERXm7OKIAoAj3YYh7sVV18xr5-Nf3UzBxHY'
    title: 'Using DataVis Grids - Data Tools'
    modifiedTime: '2020-03-16T16:31:49.734Z'
    version: 48
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'using-datavis-grids-data-tools.md'
  webscan-report.md:
    type: 'md'
    id: '1DErw1fNJ_zxpvnxFQ-ECAl7ukpHNOHQHR4i8wnOjhuA'
    title: 'WebScan Report'
    modifiedTime: '2020-02-27T20:17:24.392Z'
    version: 28
    mimeType: 'text/x-markdown'
    fileName: 'webscan-report.md'
  uncoded-medications-report.md:
    type: 'md'
    id: '1Z0c1FY1ZqEntX3pswcGHqWaRPELUHJXY_AA_bWqkRC0'
    title: 'Uncoded Medications Report'
    modifiedTime: '2020-02-27T20:17:19.653Z'
    version: 23
    mimeType: 'text/x-markdown'
    fileName: 'uncoded-medications-report.md'
  task-report.md:
    type: 'md'
    id: '1uViuWqtilTHglw0nchgu3VvxMT0Ne6OpoiyUZNe_Px4'
    title: 'Task Report'
    modifiedTime: '2020-02-27T20:17:07.946Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'task-report.md'
  storage-report.md:
    type: 'md'
    id: '1PU3KWSD2Ahv7EJS1gVzBUrMUtN8SMgMyyoHdUCzJ9t4'
    title: 'Storage Report'
    modifiedTime: '2020-02-27T20:16:58.467Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'storage-report.md'
  panel-definition-report.md:
    type: 'md'
    id: '1dIk_2xbQpzTvTX8Gy2WlTYY4TR_4q2rRg1J8Qy9e8fs'
    title: 'Panel Definition Report'
    modifiedTime: '2020-02-27T20:16:02.265Z'
    version: 24
    mimeType: 'text/x-markdown'
    fileName: 'panel-definition-report.md'
  observations-report.md:
    type: 'md'
    id: '13jOk33Y1SJkreIkd5pt3QzR7QY28FQvZOcLsMSPA1MM'
    title: 'Observations Report'
    modifiedTime: '2020-02-27T20:15:56.274Z'
    version: 24
    mimeType: 'text/x-markdown'
    fileName: 'observations-report.md'
  orders-usage-report.md:
    type: 'md'
    id: '1t7e9aucgiVOYrb6TxzA_fD1aG3VRWSNUcwJyNaENOd0'
    title: 'Orders Usage Report'
    modifiedTime: '2020-02-27T20:15:48.336Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'orders-usage-report.md'
  orders-due-report.md:
    type: 'md'
    id: '1G-25sbfgVrQHV_SoUmaYiyLGbwE2GkqCnWPRHl0q4lQ'
    title: 'Orders Due Report'
    modifiedTime: '2020-02-27T20:15:40.621Z'
    version: 53
    mimeType: 'text/x-markdown'
    fileName: 'orders-due-report.md'
  osha-300-log-report.md:
    type: 'md'
    id: '1H7WtbjdWRFk16DZx2HZK1GANzpRJH4FQiDhAuFAY4zE'
    title: 'OSHA 300 Log Report'
    modifiedTime: '2020-02-27T20:15:26.983Z'
    version: 43
    mimeType: 'text/x-markdown'
    fileName: 'osha-300-log-report.md'
  open-encounters-report.md:
    type: 'md'
    id: '1EHgA_fUZw1elKqO93WHidXgIbGAskkj0ibyxAMYVZ_Y'
    title: 'Open Encounters Report'
    modifiedTime: '2020-02-27T20:15:15.596Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'open-encounters-report.md'
  non-compliant-report.md:
    type: 'md'
    id: '1QaQQxJirP8pjxLBGGUDdiJnkcBYeMGC9uvK5TwME2po'
    title: 'Non-Compliant Report'
    modifiedTime: '2020-02-27T20:15:07.915Z'
    version: 23
    mimeType: 'text/x-markdown'
    fileName: 'non-compliant-report.md'
  medication-report.md:
    type: 'md'
    id: '1R15V9vD7TWaOwf81dKXw0Fw4EfTL6gIJGJY1o8uVwbk'
    title: 'Medication Report'
    modifiedTime: '2020-02-27T20:15:01.994Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'medication-report.md'
  meaningful-use-reports.md:
    type: 'md'
    id: '1yYiZJPGtNY3bZgy9tBkkdzQ6xFCDbhqxgYSsmaG3dgA'
    title: 'Meaningful Use Reports'
    modifiedTime: '2020-02-27T20:14:52.180Z'
    version: 34
    mimeType: 'text/x-markdown'
    fileName: 'meaningful-use-reports.md'
  inventory-transaction-report.md:
    type: 'md'
    id: '1gRYfeUHGiLquKk9t2JdT7N9FB4E6usFStodhy2VLLUg'
    title: 'Inventory Transaction Report'
    modifiedTime: '2020-02-27T20:14:45.791Z'
    version: 27
    mimeType: 'text/x-markdown'
    fileName: 'inventory-transaction-report.md'
  incidents-report.md:
    type: 'md'
    id: '1nzKPqbfce5x-xf3bIOKanzT-g7PgU9_Hf6d1AQFfmZY'
    title: 'Incidents Report'
    modifiedTime: '2020-02-27T20:14:28.257Z'
    version: 26
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'incidents-report.md'
  fill-reports.md:
    type: 'md'
    id: '14wwTc74KWcRO1SQtDG0L14yjfNTGM5pNgfFZy8_6Jko'
    title: 'Fill Reports'
    modifiedTime: '2020-02-27T20:14:19.426Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'fill-reports.md'
  exporting-report-data.md:
    type: 'md'
    id: '1uKwVExlu2rx0upDsTsYNLLFuCSVGp0LI0GHZhXXg_I0'
    title: 'Exporting Report Data'
    modifiedTime: '2020-02-27T20:14:13.281Z'
    version: 29
    mimeType: 'text/x-markdown'
    fileName: 'exporting-report-data.md'
  encounter-report.md:
    type: 'md'
    id: '1AfAIuXdoM2LLQYJ5jK8WlMIA-jqgmsn12YeAm6Tj_wQ'
    title: 'Encounter Report'
    modifiedTime: '2020-02-27T20:14:04.456Z'
    version: 27
    mimeType: 'text/x-markdown'
    fileName: 'encounter-report.md'
  e-meds-report.md:
    type: 'md'
    id: '1fNg0sAfSa--FDnU7IhltWryuzjmLbiqj7K7tEymrRSA'
    title: 'E-Meds Report'
    modifiedTime: '2020-02-27T20:13:34.072Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'e-meds-report.md'
  dictation-without-transcription-report.md:
    type: 'md'
    id: '1QmHuie56PpaTx4U5VitJGztEabDIhpA7ukvq0Jj_eP4'
    title: 'Dictation without Transcription Report'
    modifiedTime: '2020-02-27T20:13:16.359Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'dictation-without-transcription-report.md'
  conditions-icd-9-report.md:
    type: 'md'
    id: '1khW9jXd8a8psZUg1FhRqHGGIGdvDgSSU9xhzRsT5ofE'
    title: 'Conditions/ICD-9 Report'
    modifiedTime: '2020-02-27T20:13:04.136Z'
    version: 30
    mimeType: 'text/x-markdown'
    fileName: 'conditions-icd-9-report.md'
  common-case-search-report.md:
    type: 'md'
    id: '1qJ77x6h2bKHr-1OAJ9qGOMRhuv2D5WKtevsdQ22z1RU'
    title: 'Common Case Search Report'
    modifiedTime: '2020-02-27T20:12:56.822Z'
    version: 80
    mimeType: 'text/x-markdown'
    fileName: 'common-case-search-report.md'
  appointment-report.md:
    type: 'md'
    id: '16bxQgq2-0OvXmyQcnJK81ci7x-uFmu3AQBhmAbLaa30'
    title: 'Appointment Report'
    modifiedTime: '2020-02-27T20:12:25.056Z'
    version: 54
    mimeType: 'text/x-markdown'
    fileName: 'appointment-report.md'
  additional-appointment-related-reports.md:
    type: 'md'
    id: '1HZLlidMJpPlgDUKxH56ywGr29SsIf3WwPZk_EctSTaI'
    title: 'Additional Appointment-Related Reports'
    modifiedTime: '2020-02-27T20:12:13.662Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'additional-appointment-related-reports.md'
  activity-log-report.md:
    type: 'md'
    id: '1kGherkQEZsAMDqFYdzHWmlePSKnIhjiReBA8p635AgY'
    title: 'Activity Log Report'
    modifiedTime: '2020-02-27T20:12:05.387Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'activity-log-report.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
