type: 'directory'
id: '1pvPT-h2FyQecUSDWuNAy6mfOatIwj_Ju'
title: 'EHR Certification'
fileName: 'ehr-certification'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-11-15T18:19:12.857Z'
version: '79'
fileMap:
  real-world-testing.md:
    type: 'md'
    id: '181WNaOF2YKqpFmbb4SSXEOUxGi4vdCfN6xyCaYV7S3s'
    title: 'Real World Testing'
    modifiedTime: '2022-08-22T20:51:43.338Z'
    version: 12
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'real-world-testing.md'
  real-world-testing:
    type: 'directory'
    id: '1uYzQROxAcRAaC5tUMD8kTo8w9N1Lh3zh'
    title: 'Real World Testing'
    modifiedTime: '2022-08-22T20:29:29.015Z'
    version: 4
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'real-world-testing'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
