type: 'directory'
id: '1gcdDn4ndAdnO7VhG7MPO-ffepKopU-Vk'
title: 'Diagrams'
fileName: 'diagrams'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-03-30T20:09:46.150Z'
version: '83'
fileMap:
  health-surveillance.svg:
    type: 'drawing'
    id: '1oL8PInjBlkUjA_1YJkarysMMhTCajCs4QYG0zMfPm2Y'
    title: 'health-surveillance'
    modifiedTime: '2022-03-22T17:51:08.739Z'
    version: 101
    mimeType: 'image/svg+xml'
    fileName: 'health-surveillance.svg'
  eh-positioning.svg:
    type: 'drawing'
    id: '1xoFqsiEY1dao0XQJHU9KVix8mpdCXzYHcTpWM34iFlE'
    title: 'EH Positioning'
    modifiedTime: '2021-05-11T18:11:07.781Z'
    version: 136
    mimeType: 'image/svg+xml'
    fileName: 'eh-positioning.svg'
  rapid-deployment-agenda.svg:
    type: 'drawing'
    id: '1uke0wnTPcMkKLw0poL3qbRElToYx9ySQizgtk-drL_4'
    title: 'Rapid Deployment Agenda'
    modifiedTime: '2021-02-17T19:35:58.788Z'
    version: 29
    mimeType: 'image/svg+xml'
    fileName: 'rapid-deployment-agenda.svg'
  injury-care.svg:
    type: 'drawing'
    id: '12-5serCmLHEvhL0ccUoa8kB38Rkkiqya3xCmclI26hs'
    title: 'injury-care'
    modifiedTime: '2021-02-16T21:49:30.881Z'
    version: 98
    mimeType: 'image/svg+xml'
    fileName: 'injury-care.svg'
  wc-positioning.svg:
    type: 'drawing'
    id: '1oK0DP9sEpkz04k8IKJ2kOqvCZuI8QuC-VgiM_TdBZWs'
    title: 'WC Positioning'
    modifiedTime: '2021-02-03T18:47:07.578Z'
    version: 86
    mimeType: 'image/svg+xml'
    fileName: 'wc-positioning.svg'
  financial-contracting-workflow-swim-lane.svg:
    type: 'drawing'
    id: '1Ep8KXOQnZilouIXEIVOGQh4ELxTdmezSSBzKhXa4_tI'
    title: 'Financial Contracting Workflow Swim-lane'
    modifiedTime: '2020-07-02T17:00:31.953Z'
    version: 20
    mimeType: 'image/svg+xml'
    fileName: 'financial-contracting-workflow-swim-lane.svg'
  financial-swimlane.svg:
    type: 'drawing'
    id: '12S7wtAiix7dfM7q-MY4GWO44NZaXHtn0VtGhx5Lldfo'
    title: 'Financial Swimlane'
    modifiedTime: '2020-07-02T16:59:55.531Z'
    version: 24
    mimeType: 'image/svg+xml'
    fileName: 'financial-swimlane.svg'
  wc-functional_positioning.svg:
    type: 'drawing'
    id: '1pxCXem3_qPuDOZobwowmlnjTfl8xq01B2mG5VRkeqcU'
    title: 'wc-functional_positioning'
    modifiedTime: '2020-02-17T18:13:04.535Z'
    version: 253
    mimeType: 'image/svg+xml'
    fileName: 'wc-functional_positioning.svg'
  case_management.svg:
    type: 'drawing'
    id: '16uwI5R0QsUAJMK1ivuLmKZd4EDxveRBAxFseuZfBqj4'
    title: 'case_management'
    modifiedTime: '2019-05-20T18:54:04.942Z'
    version: 44
    mimeType: 'image/svg+xml'
    fileName: 'case_management.svg'
  discovery_to_quickstart.svg:
    type: 'drawing'
    id: '1tZbo9V_aDr-EzNJBBss4pkPrdb5moIvvhQ9i2gq0Zic'
    title: 'discovery_to_quickstart'
    modifiedTime: '2018-12-20T18:53:48.310Z'
    version: 65
    mimeType: 'image/svg+xml'
    fileName: 'discovery_to_quickstart.svg'
  copy-of-positioning-v1.svg:
    type: 'drawing'
    id: '1InEImxEYRGoRmXtGm8aEQKQ7kRpkGNPOiKRLT-wfjgA'
    title: 'Copy of positioning-v1'
    modifiedTime: '2018-08-14T16:13:35.091Z'
    version: 55
    mimeType: 'image/svg+xml'
    fileName: 'copy-of-positioning-v1.svg'
  positioning-v1.svg:
    type: 'drawing'
    id: '15HRIUQAACNHnxW4RNBQnJoYEHGa3c1y7Touni3UMNAs'
    title: 'positioning-v1'
    modifiedTime: '2018-07-24T03:26:57.315Z'
    version: 214
    mimeType: 'image/svg+xml'
    fileName: 'positioning-v1.svg'
  sphinx.svg:
    type: 'drawing'
    id: '1JGKHXiaSlni48L3guCUdu0TJWf4T4UQR6YgGe7pldw4'
    title: 'sphinx'
    modifiedTime: '2017-12-29T14:02:42.754Z'
    version: 30
    mimeType: 'image/svg+xml'
    fileName: 'sphinx.svg'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
