type: 'directory'
id: '1JiP8e8-zvia5AHDjEo407wsBZdKTRQc1'
title: 'VPAT'
fileName: 'vpat'
mimeType: 'application/vnd.google-apps.folder'
date: '2021-09-24T17:52:18.921Z'
version: '18'
fileMap:
  patient-portal-voluntary-product-accessibility-template-vpat.md:
    type: 'md'
    id: '1KUzYPujy6FRjGnKxGhV2JxkonNssifccodK6J5eCDMQ'
    title: 'Patient Portal Voluntary Product Accessibility Template (VPAT)'
    modifiedTime: '2021-09-24T18:00:55.885Z'
    version: 48
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'patient-portal-voluntary-product-accessibility-template-vpat.md'
  clinical-portal-voluntary-product-accessibility-template-vpat.md:
    type: 'md'
    id: '1QD4RgoH8b8es0UDe0kWLs7TXfP7mKm01rr4lo00RqYM'
    title: 'Clinical Portal Voluntary Product Accessibility Template (VPAT) '
    modifiedTime: '2021-09-24T18:00:25.665Z'
    version: 211
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'clinical-portal-voluntary-product-accessibility-template-vpat.md'
  employer-portal-voluntary-product-accessibility-template-vpat.md:
    type: 'md'
    id: '1r345knczilBhSJsSnKbhV-goCPdZe9VcoQk0Y3kss6I'
    title: 'Employer Portal Voluntary Product Accessibility Template (VPAT) '
    modifiedTime: '2021-09-24T17:59:23.773Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'employer-portal-voluntary-product-accessibility-template-vpat.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
