type: 'directory'
id: '1zkr32tiy309Y5ReMR7ectmlv7fT_DzVz'
title: 'System Email Templates'
fileName: 'system-email-templates'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:46.535Z'
version: '280'
fileMap:
  email-templates-from-scheduler.md:
    type: 'md'
    id: '1B4axGqIlA9niMn8voc7pPZy4-1TrVEX2SHZkqIRCj0E'
    title: 'Email Templates from Scheduler'
    modifiedTime: '2020-02-27T20:37:44.415Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'email-templates-from-scheduler.md'
  email-templates-from-chart.md:
    type: 'md'
    id: '1kw4fVIHlqFMCMaMAvAkjN6dnmHZjQFFx_TSi7IQAKeQ'
    title: 'Email Templates from Chart'
    modifiedTime: '2020-02-27T20:37:31.538Z'
    version: 17
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'email-templates-from-chart.md'
  email-templates-from-scheduler:
    type: 'directory'
    id: '1lbXsE4Lc4QrAiM7kYQUANJgg10rfH8UO'
    title: 'Email Templates from Scheduler'
    modifiedTime: '2020-02-27T19:24:48.880Z'
    version: 276
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'email-templates-from-scheduler'
  email-templates-from-chart:
    type: 'directory'
    id: '1Ywc4IM6HcOBPFPELtqvecR7mUCbonRzD'
    title: 'Email Templates from Chart'
    modifiedTime: '2020-02-27T19:24:47.742Z'
    version: 267
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'email-templates-from-chart'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
