type: 'directory'
id: '1uYzQROxAcRAaC5tUMD8kTo8w9N1Lh3zh'
title: 'Real World Testing'
fileName: 'real-world-testing'
mimeType: 'application/vnd.google-apps.folder'
date: '2022-08-22T20:29:29.015Z'
version: '4'
fileMap:
  rwt-results-2022-q2.md:
    type: 'md'
    id: '1Cqgy5lwUu6jZr8ta02aN69n1uWkM4InqJGdmE7w0JD8'
    title: 'RWT Results 2022 Q2'
    modifiedTime: '2022-07-15T20:23:23.964Z'
    version: 201
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'rwt-results-2022-q2.md'
  rwt-results-2022-q1.md:
    type: 'md'
    id: '1RSYz8E5xgXRhFy92EamMI501C7vV0mSHrqtTB51vwY0'
    title: 'RWT Results 2022 Q1'
    modifiedTime: '2022-07-15T19:42:49.039Z'
    version: 439
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'rwt-results-2022-q1.md'
  real-world-testing-plan-2021.md:
    type: 'md'
    id: '1JOipshX_JQAcd0HqbvE1rtXw_eTahntxdGjyJNrygjI'
    title: 'Real World Testing Plan 2021'
    modifiedTime: '2022-04-13T14:03:42.300Z'
    version: 204
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'real-world-testing-plan-2021.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
