type: 'directory'
id: '1QAgPkRaILZ91hHzR8GdW0PbcPLpt6cjz'
title: 'Application Programming Interface (API)'
fileName: 'application-programming-interface-api'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:42.109Z'
version: '129'
fileMap:
  terms-of-api-use.md:
    type: 'md'
    id: '1S1Gn8RLJor00n4SJKSewscmpauO8owVwfgY5wRsBFFY'
    title: 'Terms of API Use'
    modifiedTime: '2021-04-06T13:28:47.741Z'
    version: 67
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'terms-of-api-use.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
