type: 'directory'
id: '17-NcVAnFsowz9Jlwf3unnYeOTf_PPkXC'
title: 'Quality Reporting'
fileName: 'quality-reporting'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:42.968Z'
version: '275'
fileMap:
  brief-introduction-to-quality-reporting.md:
    type: 'md'
    id: '1gk1DvcuNmDie5Alw9zirWHeNjVL8b0aumtgO7-gq8-o'
    title: 'Brief Introduction to Quality Reporting'
    modifiedTime: '2020-02-28T17:00:04.178Z'
    version: 28
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'brief-introduction-to-quality-reporting.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
