type: 'directory'
id: '1RZD2sGFjRymsNpRb9RUWctzi58oJUXXb'
title: 'Rapid Deployment Data Migration'
fileName: 'rapid-deployment-data-migration'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:36.680Z'
version: '289'
fileMap:
  injury-and-illness-data-imports.md:
    type: 'md'
    id: '1nXrFjzTbyMi_As_lbDc5OIGFCsqmfTNLYVEQ5UDffYo'
    title: 'Injury & Illness Data Imports'
    modifiedTime: '2020-02-27T21:24:12.306Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'injury-and-illness-data-imports.md'
  historical-data-imports.md:
    type: 'md'
    id: '1jfYSK52Yc-BRue-sia-ROsKSfd30pvkFda9-bI3zfQw'
    title: 'Historical Data Imports'
    modifiedTime: '2020-02-27T21:24:09.516Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'historical-data-imports.md'
  chart-data-imports.md:
    type: 'md'
    id: '1scn3WR9Ydr9g0eDzfUu_C2JEbEEesIkjrS7jNTt6emA'
    title: 'Chart Data Imports'
    modifiedTime: '2020-02-27T21:24:06.521Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'chart-data-imports.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
