type: 'directory'
id: '1tqEOhPHt74pLMpsOkJ6BsNatBJPgq4Zy'
title: 'Communications'
fileName: 'communications'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:44.523Z'
version: '302'
fileMap:
  end-of-year-is-here-keeping-up-with-cms.md:
    type: 'md'
    id: '1mzFSt5w-9M3rZjHAehLuli0zz3d_eVNp1V2k4QLZbyk'
    title: 'End-of-Year Is Here: Keeping Up with CMS'
    modifiedTime: '2020-02-27T21:32:30.291Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'end-of-year-is-here-keeping-up-with-cms.md'
  what-you-need-to-know.md:
    type: 'md'
    id: '1l64IjN7y0I0QHoM7e8hyy80El5GBEv4DC_WN8zFGt1Q'
    title: 'What You Need to Know'
    modifiedTime: '2020-02-27T20:36:53.725Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'what-you-need-to-know.md'
  mips-pick-your-pace.md:
    type: 'md'
    id: '1iN5EvKl23ZMf2h8fIgSUDxhRrSR7ChMCCJHa6zqOxMI'
    title: 'MIPS: Pick Your Pace'
    modifiedTime: '2020-02-27T20:36:50.258Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'mips-pick-your-pace.md'
  macra-quality-payment-program-qpp.md:
    type: 'md'
    id: '12p7Iy880e45Q2ET2g2wDFFRzSW5kUkrwhO8Y77UhkfQ'
    title: 'MACRA: Quality Payment Program (QPP)'
    modifiedTime: '2020-02-27T20:36:42.236Z'
    version: 34
    mimeType: 'text/x-markdown'
    fileName: 'macra-quality-payment-program-qpp.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
