type: 'directory'
id: '1rIuz5kM666moOI4oIV7hxHtJoCJsONt9'
title: 'Medical Programs'
fileName: 'medical-programs'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:53.251Z'
version: '90'
fileMap:
  clinical-medicine.md:
    type: 'md'
    id: '1D2Tr1fpF7oqAx0hsXkwT5D2RA1epjcGuNFVNv87bXEM'
    title: 'Clinical Medicine'
    modifiedTime: '2020-02-27T19:30:05.023Z'
    version: 25
    mimeType: 'text/x-markdown'
    fileName: 'clinical-medicine.md'
  occupational-medicine.md:
    type: 'md'
    id: '1VhdbTx-CN21VofK5OI8hM7_t8ZE931BH-CjqQsi0-B0'
    title: 'Occupational Medicine'
    modifiedTime: '2020-02-27T19:29:51.294Z'
    version: 26
    mimeType: 'text/x-markdown'
    fileName: 'occupational-medicine.md'
  occupational-medicine:
    type: 'directory'
    id: '1Ri5FCYaZKyz_rLQcaYI18cN2pU6dq8qb'
    title: 'Occupational Medicine'
    modifiedTime: '2020-02-27T19:23:54.746Z'
    version: 84
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'occupational-medicine'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
