type: 'directory'
id: '1lT8VTuGvwfUaQR3aSt4oPPse7myKECfi'
title: 'Medical Surveillance'
fileName: 'medical-surveillance'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:57.154Z'
version: '53'
fileMap:
  industrial-hygiene.md:
    type: 'md'
    id: '1FX0JsAMgCM3eR72z_GaADq7vNcz-_W6Ao_Y6pVj6O5A'
    title: 'Industrial Hygiene'
    modifiedTime: '2020-03-05T15:56:04.336Z'
    version: 32
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'industrial-hygiene.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
