type: 'directory'
id: '1Ia4xI0icUOir7nUhAoOsh1xa724AYseT'
title: 'E-Sign (Electronic Signature)'
fileName: 'e-sign-electronic-signature'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:17.246Z'
version: '227'
fileMap:
  e-sign-chart-tab.md:
    type: 'md'
    id: '1qLRL-ZXgf_YMeThPv-seb8y23iiKyhda6jxHnOpWzx0'
    title: 'E-Sign Chart Tab'
    modifiedTime: '2020-03-16T16:01:07.523Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'e-sign-chart-tab.md'
  request-e-signature.md:
    type: 'md'
    id: '1euO-n8bAKbLv_aPvr0MAhALo7WCGiQ1dEwtZSIpxs8c'
    title: 'Request E-Signature'
    modifiedTime: '2020-03-10T14:26:13.228Z'
    version: 60
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'request-e-signature.md'
  un-request-unassign-an-e-signature.md:
    type: 'md'
    id: '1YflmQxR-DMLdAadYA4R30YwKod3gCrhgS1Tb-8Lr-8I'
    title: 'Un-Request/Unassign an E-Signature'
    modifiedTime: '2020-03-10T14:24:17.209Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'un-request-unassign-an-e-signature.md'
  pending-e-sign-reviews.md:
    type: 'md'
    id: '1lEVwWXjC5fHEqff8amLbCXcRZK4I1-81u7xRPEs6s8I'
    title: 'Pending E-Sign Reviews'
    modifiedTime: '2020-03-10T14:22:54.163Z'
    version: 55
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'pending-e-sign-reviews.md'
  e-sign-all-pending-tab.md:
    type: 'md'
    id: '1DepI9YVtfst5VTBsH24GZilzfqqzTMmvw8GYf-yq1R4'
    title: 'E-Sign All Pending Tab'
    modifiedTime: '2020-03-10T14:20:34.885Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'e-sign-all-pending-tab.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
