type: 'directory'
id: '1KFshTO2ut-_1U5VmA9XzS4J5TZjtLgXe'
title: 'Data Migration'
fileName: 'data-migration'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:31.127Z'
version: '275'
fileMap:
  chart-data-csv-api.md:
    type: 'md'
    id: '1Jv5jf4al_rY2ZMYQmBYEW-DWpyJudarkxKZ8sbg_uSs'
    title: 'Chart Data CSV API'
    modifiedTime: '2022-06-25T15:23:12.195Z'
    version: 77
    mimeType: 'text/x-markdown'
    lastAuthor: 'Bridget Hamm'
    fileName: 'chart-data-csv-api.md'
  chart-data-csv-header-options.md:
    type: 'md'
    id: '1dVS4ah3VUay6OaQIpuyb7wwbErgLn4ko4U-MnPbQUho'
    title: 'Chart Data CSV Header Options'
    modifiedTime: '2022-06-15T16:48:55.681Z'
    version: 592
    mimeType: 'text/x-markdown'
    lastAuthor: 'Bridget Hamm'
    fileName: 'chart-data-csv-header-options.md'
  data-import-standards.md:
    type: 'md'
    id: '1WLg2T3kafPU5DrzAkrTOOMQm_2iTyBV1dJWa2ttHu2M'
    title: 'Data Import Standards'
    modifiedTime: '2022-04-04T13:01:42.605Z'
    version: 51
    mimeType: 'text/x-markdown'
    lastAuthor: 'sriecke'
    fileName: 'data-import-standards.md'
  genericimporttestpur-b.csv:
    type: 'binary'
    id: '1KIMrmLjp58wyKxLZEebiQoY6iLPvG4Lw'
    title: 'GenericImportTestPUR B.csv'
    modifiedTime: '2022-03-23T13:38:56.000Z'
    version: 80
    mimeType: 'text/csv'
    fileName: 'genericimporttestpur-b.csv'
  genericimporttestpur-a.csv:
    type: 'binary'
    id: '146dlnHSaMpVmSybF84dGx03cnrOXIeoF'
    title: 'GenericImportTestPUR A.csv'
    modifiedTime: '2022-03-23T13:29:07.000Z'
    version: 80
    mimeType: 'text/csv'
    fileName: 'genericimporttestpur-a.csv'
  lost-time-import-tool.md:
    type: 'md'
    id: '1Ik-K0wy3NnSPpPRMzo_iLVZYo7x1tNeemPQBOgJ7pAk'
    title: 'Lost Time Import Tool'
    modifiedTime: '2022-03-08T18:36:59.785Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nick Wallace'
    fileName: 'lost-time-import-tool.md'
  order-question-import-tool.md:
    type: 'md'
    id: '1vLkcD7KVc8tHY6VZkVDbXirqGFbPMPUr97U68k6Tc-c'
    title: 'Order Question Import Tool'
    modifiedTime: '2021-10-29T16:01:13.157Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: 'Kate Barton'
    fileName: 'order-question-import-tool.md'
  import-export-json-files.md:
    type: 'md'
    id: '13Oulcj0nZoB3rk_Fc-Fd4FxrUr5Di_UXZM45NP3tde4'
    title: 'Import/Export JSON Files'
    modifiedTime: '2021-08-26T12:03:20.282Z'
    version: 51
    mimeType: 'text/x-markdown'
    lastAuthor: 'sriecke'
    fileName: 'import-export-json-files.md'
  order-list-import-tool.md:
    type: 'md'
    id: '1G40DAPnlx7F9X5xRDxMUVkRSk50Ec_5HEyUdvk7yK_I'
    title: 'Order List Import Tool'
    modifiedTime: '2021-07-12T12:50:04.389Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: 'Dave Cornewell'
    fileName: 'order-list-import-tool.md'
  data-migration-overview.md:
    type: 'md'
    id: '1FKm7Me6ryOw_1L4ja8i1Oj9NXzfRld-ybN-SDmcxpX8'
    title: 'Data Migration Overview'
    modifiedTime: '2020-03-17T16:06:56.394Z'
    version: 38
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'data-migration-overview.md'
  summary-documents-csv-api.md:
    type: 'md'
    id: '1ldetcPu_lIhcsvJ_o50EZMbG_O5VN717UAv0IrPzzC4'
    title: 'Summary Documents CSV API'
    modifiedTime: '2020-03-17T15:37:53.190Z'
    version: 64
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'summary-documents-csv-api.md'
  pft-data-csv-api.md:
    type: 'md'
    id: '1DUt0OeVBqIqltcPnvfiIuZ_4zvvX5E8Y4JvqlUV9l2o'
    title: 'PFT Data CSV API'
    modifiedTime: '2020-03-17T15:18:25.223Z'
    version: 29
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'pft-data-csv-api.md'
  panel-status-import.md:
    type: 'md'
    id: '1eIHNqGUb4LBiyFjmzFyYz3svkEmx8y-Fo1I_mL9MWBQ'
    title: 'Panel Status Import'
    modifiedTime: '2020-03-17T15:16:03.508Z'
    version: 30
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'panel-status-import.md'
  observation-codes-csv-api.md:
    type: 'md'
    id: '1CotwhF-uu0oYAPV6NtTEuvP5du6OU-QEr2YW1TILwkc'
    title: 'Observation Codes CSV API'
    modifiedTime: '2020-03-17T15:10:49.614Z'
    version: 41
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'observation-codes-csv-api.md'
  injections-csv-api.md:
    type: 'md'
    id: '1aHRZ8aidsnDJ4vg1Diu1ktw9jMC_R1Q6JrPghbuckuE'
    title: 'Injections CSV API'
    modifiedTime: '2020-03-17T15:04:17.378Z'
    version: 45
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'injections-csv-api.md'
  clinical-encounter-csv-api.md:
    type: 'md'
    id: '1dWlxZTkN0MeMsw_OGuzzr2SIH6GiA3vPwndilFkY5hk'
    title: 'Clinical Encounter CSV API'
    modifiedTime: '2020-03-17T13:11:47.649Z'
    version: 32
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'clinical-encounter-csv-api.md'
  create-language-translation-file-for-import.md:
    type: 'md'
    id: '1gw2TaukmbchitBFj-iiALpqsD2Xhj4zDCqoZi0iJT2A'
    title: 'Create Language Translation File for Import'
    modifiedTime: '2020-03-17T03:19:40.137Z'
    version: 33
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-language-translation-file-for-import.md'
  panel-membership-import-tool.md:
    type: 'md'
    id: '1kF3jZSVDWJL7AYRVYHwooNNnMdOkGy8j9ACvgEH1M0Y'
    title: 'Panel Membership Import Tool'
    modifiedTime: '2020-03-17T03:14:54.850Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'panel-membership-import-tool.md'
  data-import-tab.md:
    type: 'md'
    id: '1BrKs6e4cOvDJiao6uAJib7mYJ1sROSQds2wEI6SS35Y'
    title: 'Data Import Tab'
    modifiedTime: '2020-03-17T03:04:04.539Z'
    version: 82
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'data-import-tab.md'
  ccr-document-import.md:
    type: 'md'
    id: '1WXvPYGq4hqG02LDQYHH7epqUgWwPDfB_1BVYf3121SU'
    title: 'CCR Document Import'
    modifiedTime: '2020-03-17T02:55:52.956Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'ccr-document-import.md'
  create-cases-file-for-import.md:
    type: 'md'
    id: '12tRrL1GGMV0Hp0HQOhS4zdkbS1-fbnKf2kAroBdMqZc'
    title: 'Create Cases File for Import'
    modifiedTime: '2020-03-17T02:53:32.574Z'
    version: 39
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-cases-file-for-import.md'
  create-vital-signs-file-for-import.md:
    type: 'md'
    id: '1SsFJhFp4cUoRKLIULnvccNLyYB7TpnevOHj4EJMwSJU'
    title: 'Create Vital Signs File for Import'
    modifiedTime: '2020-03-17T02:50:33.797Z'
    version: 35
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-vital-signs-file-for-import.md'
  create-pft-data-file-for-import.md:
    type: 'md'
    id: '16GPTNe8X-gfZywsQSEG5rOD6ccCOx283XiGJ9l9NfOw'
    title: 'Create PFT Data File for Import'
    modifiedTime: '2020-03-17T02:47:24.604Z'
    version: 35
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-pft-data-file-for-import.md'
  create-audiometric-data-file-for-import.md:
    type: 'md'
    id: '1pqlmPPQPZeiKt_N7XDccPfdFT5zLskxOKriIx-Nc8W4'
    title: 'Create Audiometric Data File for Import'
    modifiedTime: '2020-03-17T02:43:45.578Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-audiometric-data-file-for-import.md'
  create-health-surveillance-file-for-import.md:
    type: 'md'
    id: '1fOpOgUVCm1HHYNzZtFXrsYYmXLeEXK6McovQn-bTgQY'
    title: 'Create Health Surveillance File for Import'
    modifiedTime: '2020-03-17T02:39:10.700Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-health-surveillance-file-for-import.md'
  create-employees-file-for-import.md:
    type: 'md'
    id: '1EeSZUgogLCUZD4CFQgP3qTtmhXuvTUbD9TY7toefUAQ'
    title: 'Create Employees File for Import'
    modifiedTime: '2020-03-17T02:34:35.428Z'
    version: 41
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'create-employees-file-for-import.md'
  completed-orders-import-tool.md:
    type: 'md'
    id: '1kGK2cFMtPN8GSfO9bTam5OR7Kzc26nnEnAh1LKT2uVI'
    title: 'Completed Orders Import Tool'
    modifiedTime: '2020-03-17T02:25:23.687Z'
    version: 43
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'completed-orders-import-tool.md'
  mie-file-import.md:
    type: 'md'
    id: '1pnpaUXzHf6UilobVMr2RTHB0j2NJAafIXI5IYmfhMkY'
    title: 'MIE File Import'
    modifiedTime: '2020-03-17T02:05:30.422Z'
    version: 55
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'mie-file-import.md'
  data-migration-file-format-standard.md:
    type: 'md'
    id: '1d6JDOjLPbEZ4hDhR-Qj9-DmT3-zskOyTRgJQaYmTfYg'
    title: 'Data Migration File Format Standard'
    modifiedTime: '2020-03-17T01:50:37.727Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'data-migration-file-format-standard.md'
  data-migration-questionnaire.md:
    type: 'md'
    id: '1IDuyacdPCdTfT5pYmQkyf1icZqYTFngDpJzykC1evvg'
    title: 'Data Migration Questionnaire'
    modifiedTime: '2020-03-17T00:54:23.101Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'data-migration-questionnaire.md'
  observations-validation-test-script.md:
    type: 'md'
    id: '1RjJm78kYrjXJPlfpc7oRo0-g12BxQB5A5d7e7sTpPfM'
    title: 'Observations Validation Test Script'
    modifiedTime: '2020-02-28T15:30:47.082Z'
    version: 49
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'observations-validation-test-script.md'
  chart-relations-csv-api.md:
    type: 'md'
    id: '1FeHqSQOLwrYVUNALv6-FE9glcnBAUgFSbJxwzpiba_k'
    title: 'Chart Relations CSV API'
    modifiedTime: '2020-02-28T15:25:48.497Z'
    version: 34
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'chart-relations-csv-api.md'
  chart-medical-record-number-mrn-import-options.md:
    type: 'md'
    id: '1XdXZjpMl-nFhbNqYVZfRqVDD1-sCjB5Rrol0ohYGe7E'
    title: 'Chart Medical Record Number (MRN) Import Options'
    modifiedTime: '2020-02-28T15:25:27.336Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'chart-medical-record-number-mrn-import-options.md'
  document-validation-test-script.md:
    type: 'md'
    id: '1Is5FLQOhjm41qI_Epg9Ki6wnUfxh897DBx1zbwwO8fw'
    title: 'Document Validation Test Script'
    modifiedTime: '2020-02-27T21:33:01.890Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'document-validation-test-script.md'
  allergy-data-validation-test-script.md:
    type: 'md'
    id: '1SxK7srGGnHEu_j3yENZoNf51Uy53jy0g0iDpJZLobeM'
    title: 'Allergy Data Validation Test Script'
    modifiedTime: '2020-02-27T21:32:57.175Z'
    version: 29
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'allergy-data-validation-test-script.md'
  audiogram-validation-test-script.md:
    type: 'md'
    id: '1g7ac-0fYJZz78LbTF6XkBU9gnOXObzb1_l9cZCO33eo'
    title: 'Audiogram Validation Test Script'
    modifiedTime: '2020-02-27T21:32:53.730Z'
    version: 41
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'audiogram-validation-test-script.md'
  nature-of-injury-csv-api.md:
    type: 'md'
    id: '1TMIp_Sy8YO8Qe8FyfpxRuHIZUFUBzdSK69mRQrBUgmU'
    title: 'Nature of Injury CSV API'
    modifiedTime: '2020-02-27T21:32:25.970Z'
    version: 25
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'nature-of-injury-csv-api.md'
  conditions-csv-api.md:
    type: 'md'
    id: '1-8GONLFjnSIAyxTcEnkktUluwfAzhYBp7QrMgGLLRm4'
    title: 'Conditions CSV API'
    modifiedTime: '2020-02-27T21:32:21.297Z'
    version: 23
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'conditions-csv-api.md'
  accommodations-csv-api.md:
    type: 'md'
    id: '1rVOLi3blPwvbLbidZxdCxn58hZgU1HraWdGz-LQJJUc'
    title: 'Accommodations CSV API'
    modifiedTime: '2020-02-27T21:32:16.770Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'accommodations-csv-api.md'
  restrictions-csv-api.md:
    type: 'md'
    id: '1tJLybb-43t9zEG8lXOCUZTjbECoea4N6EhC6FIwOfqU'
    title: 'Restrictions CSV API'
    modifiedTime: '2020-02-27T21:32:12.910Z'
    version: 22
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'restrictions-csv-api.md'
  case-management-csv-api.md:
    type: 'md'
    id: '1AsEPbkLvKFI-gXp8bfQyRKL5__dnLrj_L2BDtrZg6HM'
    title: 'Case Management CSV API'
    modifiedTime: '2020-02-27T21:32:08.466Z'
    version: 24
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'case-management-csv-api.md'
  system-conversion.md:
    type: 'md'
    id: '12BfxOgwAp35VUX7a-OHkI2NB6mjuLK1ocGaJMTL0_jE'
    title: 'System Conversion'
    modifiedTime: '2020-02-27T21:31:21.718Z'
    version: 68
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'system-conversion.md'
  chart-observations-import-options.md:
    type: 'md'
    id: '179G5TF3s37IzqNSRNBCsaa4GK6r678N4gB1dBk4TB_A'
    title: 'Chart Observations Import Options'
    modifiedTime: '2020-02-27T21:31:09.639Z'
    version: 31
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'chart-observations-import-options.md'
  pharmacy-filter-import.md:
    type: 'md'
    id: '1LCFeOZz-oM3zqHHPhTmV523I3AsTJPjz5CPa9gpqB9A'
    title: 'Pharmacy Filter Import'
    modifiedTime: '2020-02-27T21:30:59.551Z'
    version: 20
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'pharmacy-filter-import.md'
  data-import-master-list.md:
    type: 'md'
    id: '12Y_7GUv00rJ2bDtFWGIHOpERDbH4nQeBH4uQI0gJ91Y'
    title: 'Data Import Master List'
    modifiedTime: '2020-02-27T21:30:54.076Z'
    version: 116
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'data-import-master-list.md'
  data-import-overview.md:
    type: 'md'
    id: '1XAl3AqJTGB3Hb7Cfm_ix2IOxF2hE23GI_ysA3cX8ZJk'
    title: 'Data Import Overview'
    modifiedTime: '2020-02-27T21:30:32.809Z'
    version: 24
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'data-import-overview.md'
  lab-result-csv-api.md:
    type: 'md'
    id: '1FwypV9LIggTF83AUXioRUfLhtpziIfE164wAE3T6uZk'
    title: 'Lab Result CSV API'
    modifiedTime: '2020-02-27T21:28:38.594Z'
    version: 31
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'lab-result-csv-api.md'
  chart-observations-default-values.md:
    type: 'md'
    id: '1pWG1xFZ_-nRK864dudkGxbyLgAzlfHPsdu2clCou-mM'
    title: 'Chart Observations Default Values'
    modifiedTime: '2020-02-27T21:04:46.860Z'
    version: 39
    mimeType: 'text/x-markdown'
    fileName: 'chart-observations-default-values.md'
  custom-documents-csv-api.md:
    type: 'md'
    id: '1l0ydyWzazhlWSBsaaS0P5LPYpI6VLb8xkNO2pZvX3q0'
    title: 'Custom Documents CSV API'
    modifiedTime: '2020-02-27T21:00:26.519Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'custom-documents-csv-api.md'
  observation-import.md:
    type: 'md'
    id: '1x2tU52MiV1lV7D3azyXfuQCtKzdiNjFfPHQUxMlnCLs'
    title: 'Observation Import'
    modifiedTime: '2020-02-27T20:46:16.207Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'observation-import.md'
  fee-schedule-import-tool.md:
    type: 'md'
    id: '1N6H4YEgK5O5BzM2oWsVL-k6RTG8KUlGVUaqjP1sC5r0'
    title: 'Fee Schedule Import Tool'
    modifiedTime: '2020-02-27T20:46:06.612Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'fee-schedule-import-tool.md'
  appointments-import.md:
    type: 'md'
    id: '1wlGTWg0_1ZGOb8zpDBEoR9M5hK8u9Rp9FlGi20Kf-bo'
    title: 'Appointments Import'
    modifiedTime: '2020-02-27T20:45:50.310Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'appointments-import.md'
  audiometric-data-csv-api.md:
    type: 'md'
    id: '14Q9LWFz8E5pjz1_Is_4mpmATDyGNYo7Jb178BZukbTA'
    title: 'Audiometric Data CSV API'
    modifiedTime: '2020-02-27T20:45:01.208Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'audiometric-data-csv-api.md'
  patient-chart-file-export.md:
    type: 'md'
    id: '1EOhzGm1utIoDgMwAXYSgX21_R9PjjHjGErpdw56hqUM'
    title: 'Patient Chart File Export'
    modifiedTime: '2020-02-27T20:24:55.247Z'
    version: 35
    mimeType: 'text/x-markdown'
    fileName: 'patient-chart-file-export.md'
  export-import-health-surveillance-panels.md:
    type: 'md'
    id: '1j39ny5DDziJwxeD0un6Js_fsVo6zi4TPZO39svw95oU'
    title: 'Export/Import Health Surveillance Panels'
    modifiedTime: '2020-02-27T20:23:52.293Z'
    version: 32
    mimeType: 'text/x-markdown'
    fileName: 'export-import-health-surveillance-panels.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
