type: 'directory'
id: '1EgCM1yWElBTgEhlKFrUM5XvBBJm-AnLi'
title: 'Compliance Programs'
fileName: 'compliance-programs'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:55.871Z'
version: '60'
fileMap:
  medical-surveillance-program.md:
    type: 'md'
    id: '161HYbm5aR9SRHIzLUExrLxy-5oT0_OEABIdSSsRPVLg'
    title: 'Medical Surveillance Program'
    modifiedTime: '2022-01-04T16:29:24.385Z'
    version: 53
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'medical-surveillance-program.md'
  absence-management.md:
    type: 'md'
    id: '1r3l2pmS7U-rYZe8ZNf8ETPpuYh1F2OH7eaX3nZl-92s'
    title: 'Absence Management'
    modifiedTime: '2020-02-27T19:30:47.430Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'absence-management.md'
  worksite-injury-and-illness.md:
    type: 'md'
    id: '11c7LYNpC6JP7pLJuiK9RWaFFr6CN20w9S0z9t5hvN8o'
    title: 'Worksite Injury & Illness'
    modifiedTime: '2020-02-27T19:30:22.045Z'
    version: 22
    mimeType: 'text/x-markdown'
    fileName: 'worksite-injury-and-illness.md'
  medical-surveillance:
    type: 'directory'
    id: '1lT8VTuGvwfUaQR3aSt4oPPse7myKECfi'
    title: 'Medical Surveillance'
    modifiedTime: '2020-02-27T19:23:57.154Z'
    version: 53
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'medical-surveillance'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
