type: 'directory'
id: '1fzNZ2zmWWe3SvUsZlOoBGw7RRRDun2F5'
title: 'System Specifications'
fileName: 'system-specifications'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:40.082Z'
version: '61'
fileMap:
  application-programming-interface-api.md:
    type: 'md'
    id: '1buEjhEqeF7YkD4D8XltrDAHKHNbfICRz9wGqUqMz2ks'
    title: 'Application Programming Interface (API)'
    modifiedTime: '2022-08-30T20:43:59.305Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: 'Will Reiske'
    fileName: 'application-programming-interface-api.md'
  client-hardware-and-software-specifications.md:
    type: 'md'
    id: '1CTTLtSkn62lO5ymmKxUdGd7K1TmU70E-wYZhPt6vpIA'
    title: 'Client Hardware and Software Specifications'
    modifiedTime: '2022-08-30T20:38:36.509Z'
    version: 34
    mimeType: 'text/x-markdown'
    lastAuthor: 'Will Reiske'
    fileName: 'client-hardware-and-software-specifications.md'
  interface-specifications.md:
    type: 'md'
    id: '1dpBE40WHHZcXc2vs9jWtBsoHS-4NiCZPKXLbmG8-HX4'
    title: 'Interface Specifications'
    modifiedTime: '2022-08-25T20:50:59.221Z'
    version: 1183
    mimeType: 'text/x-markdown'
    lastAuthor: 'Tom Slabach'
    fileName: 'interface-specifications.md'
  ccda,-ccd-and-ccr-compatibility.md:
    type: 'md'
    id: '1Uk4ZHLX68xzYUxKdfF2RyJm2wURwuTz18RhBo71CgLA'
    title: 'CCDA, CCD and CCR Compatibility'
    modifiedTime: '2022-08-17T01:10:54.726Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'ccda,-ccd-and-ccr-compatibility.md'
  fhir-application-programming-interface-api.md:
    type: 'md'
    id: '14vy3k0f0EWCGaXu__JfC9ZtWZSsVFxInvTev8gQssbQ'
    title: 'FHIR Application Programming Interface (API)'
    modifiedTime: '2022-07-26T17:15:48.882Z'
    version: 40
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nicole Richardson'
    fileName: 'fhir-application-programming-interface-api.md'
  fhir-application-programming-interface-api:
    type: 'directory'
    id: '1uWsxZgKQn5wnb5Wa81Y4xDUvFsa02rBf'
    title: 'FHIR Application Programming Interface (API)'
    modifiedTime: '2022-07-26T17:07:34.356Z'
    version: 25
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'fhir-application-programming-interface-api'
  chart-pur-import-options.md:
    type: 'md'
    id: '1HFEQEZgI72Fl5H3njRaQOgoLYNAIWkZenoyeiwMAR4s'
    title: 'Chart PUR Import Options'
    modifiedTime: '2022-03-23T13:50:21.681Z'
    version: 29
    mimeType: 'text/x-markdown'
    lastAuthor: 'Kate Barton'
    fileName: 'chart-pur-import-options.md'
  copy-of-chart-pur-import-options.md:
    type: 'md'
    id: '1443DXeg-pRblb0RQHKhKofLogIbHbo3ScCmCEQZN7ts'
    title: 'Copy of Chart PUR Import Options'
    modifiedTime: '2022-03-23T13:45:45.164Z'
    version: 19
    mimeType: 'text/x-markdown'
    lastAuthor: 'Kate Barton'
    fileName: 'copy-of-chart-pur-import-options.md'
  ehr-certification:
    type: 'directory'
    id: '1pvPT-h2FyQecUSDWuNAy6mfOatIwj_Ju'
    title: 'EHR Certification'
    modifiedTime: '2021-11-15T18:19:12.857Z'
    version: 79
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'ehr-certification'
  vpat:
    type: 'directory'
    id: '1JiP8e8-zvia5AHDjEo407wsBZdKTRQc1'
    title: 'VPAT'
    modifiedTime: '2021-09-24T17:52:18.921Z'
    version: 18
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'vpat'
  system-email-templates.md:
    type: 'md'
    id: '1HdzZ_10IaQ9bJp4QxL9Cg2dVsXUao9FLoNRxH1e3SRs'
    title: 'System Email Templates'
    modifiedTime: '2020-02-27T21:26:58.722Z'
    version: 31
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'system-email-templates.md'
  on-premise-deployment.md:
    type: 'md'
    id: '1W32Q90BZqGacjJHvzQiKrDRBIvh47oBt5LK4gwHK5HI'
    title: 'On-Premise Deployment'
    modifiedTime: '2020-02-27T21:26:18.802Z'
    version: 27
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'on-premise-deployment.md'
  encryption-statement.md:
    type: 'md'
    id: '15tLB374Dvnd8zPo3U-URgzCbbHjIOxekGfR71xc1dLA'
    title: 'Encryption Statement'
    modifiedTime: '2020-02-27T20:35:59.932Z'
    version: 21
    mimeType: 'text/x-markdown'
    fileName: 'encryption-statement.md'
  system-email-templates:
    type: 'directory'
    id: '1zkr32tiy309Y5ReMR7ectmlv7fT_DzVz'
    title: 'System Email Templates'
    modifiedTime: '2020-02-27T19:24:46.535Z'
    version: 282
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'system-email-templates'
  application-programming-interface-api:
    type: 'directory'
    id: '1QAgPkRaILZ91hHzR8GdW0PbcPLpt6cjz'
    title: 'Application Programming Interface (API)'
    modifiedTime: '2020-02-27T19:24:42.109Z'
    version: 129
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'application-programming-interface-api'
  on-premise-deployment:
    type: 'directory'
    id: '1UMfOTNHV9nVW9JH5JHCvh-UjklqvimJm'
    title: 'On-Premise Deployment'
    modifiedTime: '2020-02-27T19:24:41.096Z'
    version: 302
    mimeType: 'application/vnd.google-apps.folder'
    fileName: 'on-premise-deployment'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
