type: 'directory'
id: '1OCAqxWNtXZAyZ70Djd48HrObcrDoLjV2'
title: 'Imaging'
fileName: 'imaging'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:04.690Z'
version: '280'
fileMap:
  dicom-modality-work-list-mwl.md:
    type: 'md'
    id: '1p56sFJe04z4knjZh4xtZ1RbzdzLsKRaG2Ak-hfynOfs'
    title: 'DICOM Modality Work List (MWL)'
    modifiedTime: '2020-03-24T15:53:13.829Z'
    version: 51
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'dicom-modality-work-list-mwl.md'
  inbound-application-installation-dicomd.md:
    type: 'md'
    id: '1NfgcM3b-g6oyM7u28jlav8HG9XoLCaau1JmfiH_U1w4'
    title: 'Inbound Application Installation: dicomd'
    modifiedTime: '2020-03-24T15:49:30.238Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'inbound-application-installation-dicomd.md'
  techomni.md:
    type: 'md'
    id: '1yR6OLFf8CPNyo8Nl6eo-dtuzP9HhW1kv1CKyJ_jMueQ'
    title: 'TechOmni'
    modifiedTime: '2020-03-10T14:03:53.331Z'
    version: 32
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'techomni.md'
  burning-dicom-images-onto-cd-dvd.md:
    type: 'md'
    id: '1NoHN2XFMnttAEU55T8C7kceIJ3dEjCHbW-Syvht8sWw'
    title: 'Burning DICOM Images onto CD/DVD'
    modifiedTime: '2020-03-09T21:03:47.916Z'
    version: 56
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'burning-dicom-images-onto-cd-dvd.md'
  dicom-viewer.md:
    type: 'md'
    id: '1ewns-apqZ6Qp6EPtrnaVj-FixLxSNYlQ0qz4V8-zOe0'
    title: 'DICOM Viewer'
    modifiedTime: '2020-03-09T19:36:52.318Z'
    version: 44
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'dicom-viewer.md'
  dicom-setup-tab.md:
    type: 'md'
    id: '1l50g_U5m-hU-hGjQ9Rm_xNeSY8ak62UNcqWRSTpvCbg'
    title: 'DICOM Setup Tab'
    modifiedTime: '2020-03-09T19:34:25.790Z'
    version: 35
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'dicom-setup-tab.md'
  radomni.md:
    type: 'md'
    id: '1mTsD1oXYnV2ZVK_7okDnVLmvkG60cAj5x0-DwUypgk8'
    title: 'RadOmni'
    modifiedTime: '2020-02-27T21:01:07.965Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'radomni.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
