type: 'directory'
id: '1DD9YzKQU6V3gX0kfSPC_rXkamScMbqAn'
title: 'Order & Result Management'
fileName: 'order-and-result-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:13.077Z'
version: '307'
fileMap:
  observation-flowsheets.md:
    type: 'md'
    id: '15JYECf24zEJLUoOZ9IeFZmQI2nc5yl8_dwpKAKGbIyY'
    title: 'Observation Flowsheets'
    modifiedTime: '2022-08-23T15:08:57.414Z'
    version: 310
    mimeType: 'text/x-markdown'
    lastAuthor: 'Marie Roe'
    fileName: 'observation-flowsheets.md'
  flowsheets-editor.md:
    type: 'md'
    id: '1hjjHvWq5vUEm0hyKXwjoSIMQetroCJIq1WeesFBT-CY'
    title: 'Flowsheets Editor'
    modifiedTime: '2021-12-17T15:27:04.732Z'
    version: 238
    mimeType: 'text/x-markdown'
    lastAuthor: 'sriecke'
    fileName: 'flowsheets-editor.md'
  observation-codes-editor.md:
    type: 'md'
    id: '1ohx3g_a0w1go9E2uDq5w7nr6-AZ-VrTZhFfiHgfdkwU'
    title: 'Observation Codes Editor'
    modifiedTime: '2020-03-13T20:07:29.409Z'
    version: 66
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'observation-codes-editor.md'
  observation-code-merging.md:
    type: 'md'
    id: '17At0A9fBSekiKBKyzhJeCmj9D1qV4PI_pVErgnroP_c'
    title: 'Observation Code Merging'
    modifiedTime: '2020-03-13T19:54:16.045Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'observation-code-merging.md'
  orders-view-recent.md:
    type: 'md'
    id: '1K1uiAnm1Wdda2zGIs1VIpS5Awq7QEheM5H1b6jMWM-k'
    title: 'Orders - View Recent'
    modifiedTime: '2020-03-13T19:51:09.115Z'
    version: 117
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'orders-view-recent.md'
  order-requests-grid.md:
    type: 'md'
    id: '199nDYD4Cbf7b43xTuYJNIEVtTkRYV9TVPWdD6JKZQnQ'
    title: 'Order Requests Grid'
    modifiedTime: '2020-03-13T19:30:15.508Z'
    version: 73
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'order-requests-grid.md'
  e-orders-refer-to-advanced-search.md:
    type: 'md'
    id: '1fpy2bWS8axvI2RAYvrKOr1g0iAJ-Lj5mO_y_fgM0EOU'
    title: 'E-Orders - Refer To Advanced Search'
    modifiedTime: '2020-03-13T19:26:45.630Z'
    version: 49
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'e-orders-refer-to-advanced-search.md'
  e-orders-add-order-requests.md:
    type: 'md'
    id: '1Kn-0evj_fBShe8r-4SO_JRo2CmY_54vEt4VTxlQLZ50'
    title: 'E-Orders - Add Order Requests'
    modifiedTime: '2020-03-13T19:22:58.979Z'
    version: 57
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'e-orders-add-order-requests.md'
  e-orders-chart-tab.md:
    type: 'md'
    id: '1vh7UsgREWhLDIYSS0IXhc9Z_2Rnzi1uplvp6c8ywc7o'
    title: 'E-Orders Chart Tab'
    modifiedTime: '2020-03-13T19:19:01.256Z'
    version: 70
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'e-orders-chart-tab.md'
  vitals-tracking-and-management.md:
    type: 'md'
    id: '1SLeZ_LCVcb4a6OpiLizIa-zwY9jFzjLQLtSuS2Iq14s'
    title: 'Vitals Tracking & Management'
    modifiedTime: '2020-03-13T17:01:29.858Z'
    version: 64
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'vitals-tracking-and-management.md'
  observations-tab.md:
    type: 'md'
    id: '13UOUobSDFmuMqHmgps91RswTip-sSvHqkiAncWNOtaw'
    title: 'Observations Tab'
    modifiedTime: '2020-02-27T20:03:08.015Z'
    version: 82
    mimeType: 'text/x-markdown'
    fileName: 'observations-tab.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
