type: 'directory'
id: '1Ri5FCYaZKyz_rLQcaYI18cN2pU6dq8qb'
title: 'Occupational Medicine'
fileName: 'occupational-medicine'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:23:54.746Z'
version: '84'
fileMap:
  medical-clearance.md:
    type: 'md'
    id: '1o9yP0CDEwr8G6Fgr5xRbbJe2TWKl4JavucDvzvIGU_c'
    title: 'Medical Clearance'
    modifiedTime: '2022-08-13T16:59:12.301Z'
    version: 46
    mimeType: 'text/x-markdown'
    lastAuthor: 'Doug Horner'
    fileName: 'medical-clearance.md'
  surveillance-procedures.md:
    type: 'md'
    id: '1ZazV-O1C7sT_Alm_cVaPWxbLBLpUz9wBXsR_-P3_uEs'
    title: 'Surveillance Procedures'
    modifiedTime: '2020-02-27T21:07:59.165Z'
    version: 27
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'surveillance-procedures.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
