type: 'directory'
id: '1CIvdAQPfRsjLtavjxAw_FWHO91hvMq3P'
title: 'TeleHealth'
fileName: 'telehealth'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-03-26T15:35:18.633Z'
version: '289'
fileMap:
  introducing-telehealth.md:
    type: 'md'
    id: '1UZCuq-p8tEPK49LAwi5PjF7xl3uud4LB3fYWvyK3rc4'
    title: 'Introducing TeleHealth'
    modifiedTime: '2020-03-31T16:54:54.418Z'
    version: 102
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'introducing-telehealth.md'
  telehealth-pricing.md:
    type: 'md'
    id: '1yqMTCU_lcitbjezmO6_9c0G1kwc88y0i74CLZFEK1VM'
    title: 'TeleHealth Pricing'
    modifiedTime: '2020-03-31T14:37:42.416Z'
    version: 56
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'telehealth-pricing.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
