type: 'directory'
id: '1jG_-SZfeYb-3g7gWGYBCjJoHObeVksKy'
title: 'Work-Related Exams'
fileName: 'work-related-exams'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:09.813Z'
version: '308'
fileMap:
  driver-fitness-determination-exam-dot.md:
    type: 'md'
    id: '1bRwhFEg-KNcg1yYAbh2I-dHAxBg3Bp08_otEKNHAPRA'
    title: 'Driver Fitness Determination Exam (DOT)'
    modifiedTime: '2020-03-12T20:38:19.609Z'
    version: 82
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'driver-fitness-determination-exam-dot.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
