type: 'directory'
id: '1lbXsE4Lc4QrAiM7kYQUANJgg10rfH8UO'
title: 'Email Templates from Scheduler'
fileName: 'email-templates-from-scheduler'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:48.880Z'
version: '276'
fileMap:
  apt-invite-reminder.md:
    type: 'md'
    id: '1GTx8ptizmxT6b9JBUtbNeTgDJiZ0-iGpK-rXUHcb4H8'
    title: 'Apt Invite Reminder'
    modifiedTime: '2020-02-27T20:40:43.578Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'apt-invite-reminder.md'
  apt-spv-reminder-15-days.md:
    type: 'md'
    id: '11EAdjb0ACri1VmtHF5v06HxKEIGQgzakuUYZMS_jlrk'
    title: 'Apt Spv Reminder 15 Days'
    modifiedTime: '2020-02-27T20:40:34.949Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-spv-reminder-15-days.md'
  apt-reminder-1-with-portal.md:
    type: 'md'
    id: '1vbZJxYSvKLYbSZKrjVhWmy_DO5wCxAjIgJEAlsiYoqc'
    title: 'Apt Reminder 1 with Portal'
    modifiedTime: '2020-02-27T20:40:30.829Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-reminder-1-with-portal.md'
  apt-reminder.md:
    type: 'md'
    id: '1W1mMo6izbKfwcB2lcX52-SyU0UpjhB-MZHo9_9MXxDI'
    title: 'Apt Reminder'
    modifiedTime: '2020-02-27T20:40:26.273Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-reminder.md'
  apt-released-to-full-duty.md:
    type: 'md'
    id: '16u-JX39xaMJKe01TbN1FWU3rMll3ASbRoZPpUp7ZYf4'
    title: 'Apt Released to Full Duty'
    modifiedTime: '2020-02-27T20:40:22.564Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-released-to-full-duty.md'
  apt-missed-required.md:
    type: 'md'
    id: '1yxmScXXEckEB5-E40arw9fkAjQ9cZbUK8TT1q8dCQIo'
    title: 'Apt Missed Required'
    modifiedTime: '2020-02-27T20:40:18.850Z'
    version: 16
    mimeType: 'text/x-markdown'
    fileName: 'apt-missed-required.md'
  apt-invitation-with-portal.md:
    type: 'md'
    id: '1_9KLm_UcpM0vQsGlOxZaccnQouL1lLgfn-KU5PeP_DI'
    title: 'Apt Invitation with Portal'
    modifiedTime: '2020-02-27T20:40:14.700Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-invitation-with-portal.md'
  apt-hs-out-of-compliance.md:
    type: 'md'
    id: '183tkF80Do9nLqnzVUYOnwKFk0QDexqzr0bqqSmwF89k'
    title: 'Apt HS Out of Compliance'
    modifiedTime: '2020-02-27T20:40:11.131Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-hs-out-of-compliance.md'
  apt-guideline-reminder.md:
    type: 'md'
    id: '1v8AzGmcED_QmF-RwhztZuJZjpq99NKLFVUkacCV474A'
    title: 'Apt Guideline Reminder'
    modifiedTime: '2020-02-27T20:40:07.206Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-guideline-reminder.md'
  apt-employee-reminder-7-days.md:
    type: 'md'
    id: '1Xd7K1lY-nw4rSesF1FLFEghZobJU3z6wk-t78xddBUU'
    title: 'Apt Employee Reminder 7 Days'
    modifiedTime: '2020-02-27T20:40:03.434Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'apt-employee-reminder-7-days.md'
  apt-employee-reminder-60-days.md:
    type: 'md'
    id: '1VECQleAY27YG3G6lVKv9N5MgTiNbpbrEMIB8piADuVA'
    title: 'Apt Employee Reminder 60 Days'
    modifiedTime: '2020-02-27T20:39:58.605Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-employee-reminder-60-days.md'
  apt-employee-reminder-30-days.md:
    type: 'md'
    id: '1L-bM3HlPu7UQOX8wk6h2YWAwWhmaK6qzkCXPRHWC77M'
    title: 'Apt Employee Reminder 30 Days'
    modifiedTime: '2020-02-27T20:39:54.571Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-employee-reminder-30-days.md'
  apt-confirmation.md:
    type: 'md'
    id: '1R5lYGh6lWozZjm6XieOIBw5H9DisckgDcPTq_BaRRZg'
    title: 'Apt Confirmation'
    modifiedTime: '2020-02-27T20:39:50.764Z'
    version: 25
    mimeType: 'text/x-markdown'
    fileName: 'apt-confirmation.md'
  apt-cancellation.md:
    type: 'md'
    id: '1LQAvQDYNP9KYnjyCjqJyGbTUxC4F2no7MXTOT-bNe0M'
    title: 'Apt Cancellation'
    modifiedTime: '2020-02-27T20:39:45.441Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'apt-cancellation.md'
  default.md:
    type: 'md'
    id: '1iPbgcQmlPVcCIVf0tAh4S1_Bna3rng0FmKsDK2Bcy1A'
    title: 'Default'
    modifiedTime: '2020-02-27T20:39:27.706Z'
    version: 19
    mimeType: 'text/x-markdown'
    fileName: 'default.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
