type: 'directory'
id: '1OX4OmJq4Lv_5g8mLjfb-U-tzJldgqeH2'
title: 'Case Management'
fileName: 'case-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:25:01.248Z'
version: '304'
fileMap:
  adding-absence-management-case.md:
    type: 'md'
    id: '1SbWKxI66KQQlCDFuTHv1UVOm0nNzGeRwQMdRBL8TaOY'
    title: 'Adding Absence Management Case'
    modifiedTime: '2021-09-30T18:35:29.344Z'
    version: 142
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'adding-absence-management-case.md'
  deleting-an-existing-case.md:
    type: 'md'
    id: '1COrMvtzP3Bgs_zJpX90Av-8I3GEqfod6FxixoLP2YVk'
    title: 'Deleting an Existing Case'
    modifiedTime: '2020-03-13T13:47:35.461Z'
    version: 50
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'deleting-an-existing-case.md'
  closing-an-existing-case.md:
    type: 'md'
    id: '1aHMqb0uesNxzc9vm-mmE5OSB4lyfi6zd4RTVOVFy2nw'
    title: 'Closing an Existing Case'
    modifiedTime: '2020-03-13T13:45:11.738Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'closing-an-existing-case.md'
  adding-osha-case.md:
    type: 'md'
    id: '1Q2noX9h3XKnZQ1eSpVOXXyBkriiJ_PvpgI_F2D3bDhg'
    title: 'Adding OSHA Case'
    modifiedTime: '2020-03-13T13:18:41.709Z'
    version: 71
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'adding-osha-case.md'
  adding-non-osha-case.md:
    type: 'md'
    id: '1aHT2IQB4BXVs4aZm1tYvWp8t3PvqPdSI-dJJ0w-nfqs'
    title: 'Adding Non-OSHA Case'
    modifiedTime: '2020-03-13T13:16:54.123Z'
    version: 50
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'adding-non-osha-case.md'
  viewing-cases.md:
    type: 'md'
    id: '1e_bKkEQX8mrCMXpTNQR8QddEBfMVgEUgQVv-x6d49Ds'
    title: 'Viewing Cases'
    modifiedTime: '2020-03-09T23:22:52.265Z'
    version: 47
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'viewing-cases.md'
  adding-msea-case.md:
    type: 'md'
    id: '1b8zEKVM7WS8b31Ur6W3sGRTxG7ZHDNFYHE3VCk32qFI'
    title: 'Adding MSEA Case'
    modifiedTime: '2020-03-09T23:04:49.437Z'
    version: 36
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'adding-msea-case.md'
  adding-hospital-case.md:
    type: 'md'
    id: '1wAgvjZdzIQWyUS1XQaiBRU4aEjN62c9TByQf8B5JJYk'
    title: 'Adding Hospital Case'
    modifiedTime: '2020-03-09T23:03:30.240Z'
    version: 38
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'adding-hospital-case.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
