type: 'directory'
id: '14Md2CPhpF2dtoJFQehD7d0Yxs1DjFhhl'
title: 'Portal Management'
fileName: 'portal-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:45.398Z'
version: '282'
fileMap:
  employer-portal-setup.md:
    type: 'md'
    id: '1FEbsPBy4cewT-M-3sUVazzJyqgUV6XfXTMY9xoKNezs'
    title: 'Employer Portal Setup'
    modifiedTime: '2021-08-27T18:32:47.675Z'
    version: 133
    mimeType: 'text/x-markdown'
    lastAuthor: 'Aris Eracleous'
    fileName: 'employer-portal-setup.md'
  applicant-portal.md:
    type: 'md'
    id: '14-E0o7EriOWL5ckmsBlBJ3TBeGgNAyV5k--2L_lPDSU'
    title: 'Applicant Portal'
    modifiedTime: '2021-03-31T21:08:57.956Z'
    version: 173
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'applicant-portal.md'
  patient-portal-first-time-setup-and-configuration.md:
    type: 'md'
    id: '1eTIUEAeY-ytsvs1oMTixISaQR2yyRnx2oEmW5nSaekc'
    title: 'Patient Portal First-Time Setup & Configuration'
    modifiedTime: '2021-03-30T13:46:32.498Z'
    version: 421
    mimeType: 'text/x-markdown'
    lastAuthor: 'Dawn Case'
    fileName: 'patient-portal-first-time-setup-and-configuration.md'
  linking-users-for-portal-access.md:
    type: 'md'
    id: '1JqNA5VF59NNFfR1yoDYA-woQj0Ovw7XkHh_BazY4cK8'
    title: 'Linking Users for Portal Access'
    modifiedTime: '2020-03-25T18:42:13.576Z'
    version: 57
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'linking-users-for-portal-access.md'
  messages-from-nmc-user.md:
    type: 'md'
    id: '1iwFDWxfDtmZRjE2Q2bdW7Jnd7q_7G9y1WmBUHML9rfM'
    title: 'Messages from NMC User'
    modifiedTime: '2020-03-11T22:32:43.569Z'
    version: 77
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'messages-from-nmc-user.md'
  kiosk.md:
    type: 'md'
    id: '1G5_D48UMtZeEnFgn9HwNxosxWLi0wTPauIEM6bUJIRs'
    title: 'Kiosk'
    modifiedTime: '2020-03-11T18:15:47.911Z'
    version: 57
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'kiosk.md'
  nomoreclipboard.md:
    type: 'md'
    id: '1BjF6NXvvzRfQtf-G77s_gu5FwvVtNl2x8RSz4cNIU3g'
    title: 'NoMoreClipboard'
    modifiedTime: '2020-02-27T20:37:24.966Z'
    version: 17
    mimeType: 'text/x-markdown'
    fileName: 'nomoreclipboard.md'
  employer-employee-second-portal-setup.md:
    type: 'md'
    id: '1j5-yy2Typ5nTe042-qplXCa05VN-815KmmGH0HIJ6rM'
    title: 'Employer/Employee Second Portal Setup'
    modifiedTime: '2020-02-27T19:50:32.374Z'
    version: 27
    mimeType: 'text/x-markdown'
    fileName: 'employer-employee-second-portal-setup.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
