type: 'directory'
id: '1cDwjsU6T6ZxvlKKxtnaUNonaj9izVIAE'
title: 'System Controls'
fileName: 'system-controls'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:30.080Z'
version: '289'
fileMap:
  setting-up-e-prescribers.md:
    type: 'md'
    id: '12E408bIFpcvsI5Nk2OXefON2y6qx5G9suTzn6ZASkXw'
    title: 'Setting Up E-Prescribers'
    modifiedTime: '2022-07-18T19:07:35.528Z'
    version: 98
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'setting-up-e-prescribers.md'
  access-control-adding,-deleting,-editing-users.md:
    type: 'md'
    id: '1LTusqsZZWBwb5luysWoX59iHdj6vpnDi3hwYnu6ikPo'
    title: 'Access Control - Adding, Deleting, Editing Users'
    modifiedTime: '2022-07-18T18:55:35.781Z'
    version: 80
    mimeType: 'text/x-markdown'
    lastAuthor: 'Alice Uhrick'
    fileName: 'access-control-adding,-deleting,-editing-users.md'
  customize-online-help-pop-up-screens.md:
    type: 'md'
    id: '13o3xyK05fHWoDwV8Z3DI4a0LtV4hNfAq3T0O7IF8J2A'
    title: 'Customize Online Help Pop-up Screens'
    modifiedTime: '2021-11-17T16:12:49.566Z'
    version: 111
    mimeType: 'text/x-markdown'
    lastAuthor: 'Aaron Capriglione'
    fileName: 'customize-online-help-pop-up-screens.md'
  partition-manager.md:
    type: 'md'
    id: '1Bt6c-VYustMe1qKSLapSrA9jDJ7z1TUAWamcS9sPzdU'
    title: 'Partition Manager'
    modifiedTime: '2021-11-11T15:00:57.459Z'
    version: 81
    mimeType: 'text/x-markdown'
    lastAuthor: 'jvaldez'
    fileName: 'partition-manager.md'
  med-web-ssl-certificate-authority.md:
    type: 'md'
    id: '1vXuEhZGQF7tWWFw2i51IR52T3PGCilU7sCPtGQbfn58'
    title: 'Med-Web SSL Certificate Authority'
    modifiedTime: '2021-10-06T02:38:47.400Z'
    version: 37
    mimeType: 'text/x-markdown'
    lastAuthor: 'Dave Cornewell'
    fileName: 'med-web-ssl-certificate-authority.md'
  document-queue-merging-imported-documents.md:
    type: 'md'
    id: '1FM-Bx8fVSojYtqK0VN_VG1R69EAzJFO05_M4uSCLGCA'
    title: 'Document Queue - Merging Imported Documents'
    modifiedTime: '2021-09-24T18:21:23.309Z'
    version: 140
    mimeType: 'text/x-markdown'
    lastAuthor: 'Nick Wallace'
    fileName: 'document-queue-merging-imported-documents.md'
  inbound-fax-queue-setting-user-access-permissions.md:
    type: 'md'
    id: '1pU-zPBkTbVV3TguLxs3JphdGkgUUx2hqlb5hv7tIRTM'
    title: 'Inbound Fax Queue - Setting User Access Permissions'
    modifiedTime: '2021-06-22T13:11:30.338Z'
    version: 62
    mimeType: 'text/x-markdown'
    lastAuthor: 'Spenser Smith'
    fileName: 'inbound-fax-queue-setting-user-access-permissions.md'
  user-provider-and-department-management.md:
    type: 'md'
    id: '1Lt21m84aiIU-XrGla23WxJDEqtnSk4WH5fRcCHuO3Nk'
    title: 'User/Provider & Department Management'
    modifiedTime: '2020-03-19T22:27:44.922Z'
    version: 88
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'user-provider-and-department-management.md'
  odbc-install-and-configuration.md:
    type: 'md'
    id: '10DpLTmdJcar4ZJVANM1AB7wCDKMtLUV3fUtrWwst2dk'
    title: 'ODBC Install & Configuration'
    modifiedTime: '2020-03-16T23:23:27.283Z'
    version: 57
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'odbc-install-and-configuration.md'
  multilingual-feature.md:
    type: 'md'
    id: '1WPu1ebqiVNNGUDb98AUfFb2E_d84QdNhfsHGhOGhojY'
    title: 'Multilingual Feature'
    modifiedTime: '2020-03-16T22:57:36.970Z'
    version: 98
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'multilingual-feature.md'
  print-manager.md:
    type: 'md'
    id: '1jBh_K3fZbn14VfTBL_kY9Ft5tgywajmZA3SmpVz3ib0'
    title: 'Print Manager'
    modifiedTime: '2020-03-16T22:51:33.990Z'
    version: 34
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'print-manager.md'
  reset-user-passwords.md:
    type: 'md'
    id: '19unVE5RmUD63_o6DY0srHZKSSROXk5WQe9OqWFJdGws'
    title: 'Reset User Passwords'
    modifiedTime: '2020-03-16T22:43:01.849Z'
    version: 62
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'reset-user-passwords.md'
  limited-access-users.md:
    type: 'md'
    id: '1gna_b2P4oKkvDN3s9XIHm9jIWxWXfK6fpQxbjamyJ9g'
    title: 'Limited Access Users'
    modifiedTime: '2020-03-16T22:39:47.027Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'limited-access-users.md'
  provider-organization-setup.md:
    type: 'md'
    id: '1nfiZ9Ext0hYvOXTu4_62icSfxRg680q9pkZyrGBZwUY'
    title: 'Provider Organization Setup'
    modifiedTime: '2020-03-16T22:35:38.380Z'
    version: 62
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'provider-organization-setup.md'
  spell-check.md:
    type: 'md'
    id: '1MJjnaHOlZVVKSlWvdcOm5CsdSttR8dvU2GFr9qk1CtQ'
    title: 'Spell Check'
    modifiedTime: '2020-03-10T14:16:20.062Z'
    version: 36
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'spell-check.md'
  merge-manager-tab.md:
    type: 'md'
    id: '1c6lN_cYM8X_X726MjhBb57B_NzKZSz-NEeNngYld0tk'
    title: 'Merge Manager Tab'
    modifiedTime: '2020-02-27T21:21:33.247Z'
    version: 42
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'merge-manager-tab.md'
  email-reminders-from-system.md:
    type: 'md'
    id: '1i7YoarhqQRnve4N65SpJkHJR9raGN_EMCMfzShpUyUw'
    title: 'Email Reminders from System'
    modifiedTime: '2020-02-27T21:21:19.649Z'
    version: 72
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'email-reminders-from-system.md'
  access-control-quick-add-multiple-active-users.md:
    type: 'md'
    id: '1YTgZIdKB74fpmIEPrcN3Z2VzvShm78X7kfxa6Yp5Jvg'
    title: 'Access Control - Quick Add Multiple Active Users'
    modifiedTime: '2020-02-27T21:20:20.800Z'
    version: 47
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'access-control-quick-add-multiple-active-users.md'
  merging-accounts-charts-in-system.md:
    type: 'md'
    id: '1c8cCEVXofjXUudcZMlnClVF1Ocn4JL3jIHFRSujRDoY'
    title: 'Merging Accounts/Charts in System'
    modifiedTime: '2020-02-27T20:22:07.557Z'
    version: 61
    mimeType: 'text/x-markdown'
    fileName: 'merging-accounts-charts-in-system.md'
  secure-email-to-whitelisted-domain-s.md:
    type: 'md'
    id: '1Ib7pJ_sdehPHpT606NGgSAwW-rwHmXJPiGGxEOjDyIQ'
    title: 'Secure Email to Whitelisted Domain(s)'
    modifiedTime: '2020-02-27T20:21:13.177Z'
    version: 58
    mimeType: 'text/x-markdown'
    fileName: 'secure-email-to-whitelisted-domain-s.md'
  view-user-audit-log.md:
    type: 'md'
    id: '1g2tVujYONeJ_nu9D91-sH1fwBjiDp22e0ToXFFWyAAo'
    title: 'View User Audit Log'
    modifiedTime: '2020-02-27T20:20:58.429Z'
    version: 33
    mimeType: 'text/x-markdown'
    fileName: 'view-user-audit-log.md'
  resource-restrictions.md:
    type: 'md'
    id: '1nnCVxIGqtmtRT3b6tppaIYa3e7iKEVVyz73HYdLR6cY'
    title: 'Resource Restrictions'
    modifiedTime: '2020-02-27T20:20:52.770Z'
    version: 36
    mimeType: 'text/x-markdown'
    fileName: 'resource-restrictions.md'
  language-tab-create-new-help-bubble-text.md:
    type: 'md'
    id: '1VujcN2rhMiBkkN8DAz4dpBmEUNObiLReSf4DVUCmfFk'
    title: 'Language Tab - Create New Help Bubble Text'
    modifiedTime: '2020-02-27T20:20:44.606Z'
    version: 32
    mimeType: 'text/x-markdown'
    fileName: 'language-tab-create-new-help-bubble-text.md'
  locking-individual-or-specific-charts.md:
    type: 'md'
    id: '15f1ifjt8uLBTe__5LgBJ4JW4-pgR8Hl1Jm6z90CREMA'
    title: 'Locking Individual or Specific Charts'
    modifiedTime: '2020-02-27T20:19:45.825Z'
    version: 48
    mimeType: 'text/x-markdown'
    fileName: 'locking-individual-or-specific-charts.md'
  emergency-access-for-limited-access-users.md:
    type: 'md'
    id: '1RHp0GCOeed1f4pcdngKoeFLYHYfi1ZzkKVkSPLRcAl8'
    title: 'Emergency Access for Limited Access Users'
    modifiedTime: '2020-02-27T20:19:38.892Z'
    version: 35
    mimeType: 'text/x-markdown'
    fileName: 'emergency-access-for-limited-access-users.md'
  adding-users-to-a-provider-organization.md:
    type: 'md'
    id: '1nJaL4WnctL26KUVyn_E4xWj40rxOtav0aUc6OCOVT8U'
    title: 'Adding Users to a Provider Organization'
    modifiedTime: '2020-02-27T20:18:45.794Z'
    version: 39
    mimeType: 'text/x-markdown'
    fileName: 'adding-users-to-a-provider-organization.md'
  add-referring-physician-users.md:
    type: 'md'
    id: '1yKC2c9EtO3QjCF8EoLF52NjXzXSlSOxQv9_d4cmU7Tc'
    title: 'Add Referring Physician Users'
    modifiedTime: '2020-02-27T20:18:08.784Z'
    version: 31
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'add-referring-physician-users.md'
  system-plugins.md:
    type: 'md'
    id: '1HYurITMVMtCBxSrZ_uqoJYIArEd2gm4FoGrr99KfC4A'
    title: 'System Plugins'
    modifiedTime: '2020-02-27T20:17:38.936Z'
    version: 23
    mimeType: 'text/x-markdown'
    fileName: 'system-plugins.md'
wikigdrive: '762e46ee0b866c028283dd665b3a8ee950fb436c'
