type: 'directory'
id: '1n0kG7SZnUulm0gKq-P4gMwaFL2rIRwLG'
title: 'Task Management'
fileName: 'task-management'
mimeType: 'application/vnd.google-apps.folder'
date: '2020-02-27T19:24:16.251Z'
version: '277'
fileMap:
  fast-task-templates.md:
    type: 'md'
    id: '1x3z6Xp7GZNw4cMJfxdhhMP4kLcj4bVEJ6w0PLZ4aEqw'
    title: 'Fast Task Templates'
    modifiedTime: '2020-03-16T15:58:58.269Z'
    version: 96
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'fast-task-templates.md'
  adding-tasks.md:
    type: 'md'
    id: '1n6mexq2OOHyGdWBYutejlrZ6IXupdbAGReupGd28Kag'
    title: 'Adding Tasks'
    modifiedTime: '2020-03-16T15:52:59.061Z'
    version: 89
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'adding-tasks.md'
  task-list.md:
    type: 'md'
    id: '1HPEy9sWojSVb5ebfsWoQ0io8hjQ7fDFZGlfi0T6xT1k'
    title: 'Task List'
    modifiedTime: '2020-03-16T15:47:13.973Z'
    version: 127
    mimeType: 'text/x-markdown'
    lastAuthor: ''
    fileName: 'task-list.md'
  task-search.md:
    type: 'md'
    id: '1kK4-VsEd_9DgH2j0H5pW-TwjwAqXTQ7gg84IjhMMszw'
    title: 'Task Search'
    modifiedTime: '2020-03-10T14:50:47.829Z'
    version: 35
    mimeType: 'text/x-markdown'
    lastAuthor: 'aquandt'
    fileName: 'task-search.md'
wikigdrive: 'eb4f9f8e82d104274f4630740771c9319ef63af0'
